import { NextResponse } from "next/server";
import { z } from "zod";
import type { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { getSessionUser } from "@/lib/session";
import { EVENT_TYPES } from "@/lib/theme";
import { recordAudit } from "@/lib/audit";

const patchSchema = z.object({ title:z.string().trim().max(120).optional().nullable(), notes:z.string().trim().max(2000).optional().nullable(), type:z.enum(EVENT_TYPES).optional(), jobId:z.string().cuid().optional().nullable(), assignedToId:z.string().cuid().optional().nullable(), startsAt:z.string().datetime().optional(), endsAt:z.string().datetime().optional() });

async function tenantActor(){const user=await getSessionUser();if(!user)return{error:NextResponse.json({error:"Unauthorized"},{status:401})};if(!user.businessId)return{error:NextResponse.json({error:"No active customer business selected."},{status:409})};return{user,businessId:user.businessId};}
async function syncCanonicalJobEvent(tx:Prisma.TransactionClient,jobId:string,businessId:string){const job=await tx.job.findFirst({where:{id:jobId,businessId},select:{id:true}});if(!job)return;const canonical=await tx.jobEvent.findFirst({where:{jobId,type:"job",job:{businessId}},orderBy:[{startsAt:"asc"},{id:"asc"}],select:{startsAt:true,endsAt:true,assignedToId:true}});if(canonical)await tx.job.updateMany({where:{id:jobId,businessId},data:{scheduledStart:canonical.startsAt,scheduledEnd:canonical.endsAt,assignedToId:canonical.assignedToId}});else await tx.job.updateMany({where:{id:jobId,businessId},data:{scheduledStart:null,scheduledEnd:null}});}

export async function PATCH(req:Request,{params}:{params:Promise<{id:string}>}){
 const a=await tenantActor();if("error" in a)return a.error;const{user,businessId}=a;const{id}=await params;
 const existing=await prisma.jobEvent.findFirst({where:{id,OR:[{job:{businessId}},{jobId:null,assignedTo:{businessId}}]},select:{id:true,jobId:true,type:true,assignedToId:true,startsAt:true,endsAt:true}});if(!existing)return NextResponse.json({error:"Event not found for this business"},{status:404});if(user.role==="EMPLOYEE"&&existing.assignedToId!==user.id)return NextResponse.json({error:"Forbidden"},{status:403});
 const parsed=patchSchema.safeParse(await req.json().catch(()=>null));if(!parsed.success||Object.keys(parsed.data).length===0)return NextResponse.json({error:"Invalid input"},{status:400});const d=parsed.data;if(user.role==="EMPLOYEE"){if(existing.type==="job"||existing.jobId)return NextResponse.json({error:"Job schedule changes must be made by an admin or supervisor"},{status:403});if(d.type!==undefined||d.jobId!==undefined||d.assignedToId!==undefined)return NextResponse.json({error:"Employees can only edit the title, notes and time of their own non-job events"},{status:403});}
 if(d.jobId){const job=await prisma.job.findFirst({where:{id:d.jobId,businessId},select:{id:true}});if(!job)return NextResponse.json({error:"Job not found for this business"},{status:404});}
 if(d.assignedToId){const assignee=await prisma.user.findFirst({where:{id:d.assignedToId,businessId,active:true},select:{id:true}});if(!assignee)return NextResponse.json({error:"Assignee not found for this business or inactive"},{status:400});}
 const nextStart=d.startsAt?new Date(d.startsAt):existing.startsAt,nextEnd=d.endsAt?new Date(d.endsAt):existing.endsAt;if(nextEnd<=nextStart)return NextResponse.json({error:"End time must be after start time"},{status:400});
 try{const event=await prisma.$transaction(async tx=>{const updated=await tx.jobEvent.update({where:{id},data:{...(d.title!==undefined?{title:d.title?.trim()||null}:{}),...(d.notes!==undefined?{notes:d.notes?.trim()||null}:{}),...(d.type?{type:d.type}:{}),...(d.jobId!==undefined?{jobId:d.jobId}:{}),...(d.assignedToId!==undefined?{assignedToId:d.assignedToId}:{}),...(d.startsAt?{startsAt:new Date(d.startsAt)}:{}),...(d.endsAt?{endsAt:new Date(d.endsAt)}:{})},select:{id:true,title:true,notes:true,jobId:true,type:true,assignedToId:true,startsAt:true,endsAt:true}});const ids=new Set<string>();if(existing.type==="job"&&existing.jobId)ids.add(existing.jobId);if(updated.type==="job"&&updated.jobId)ids.add(updated.jobId);for(const jobId of ids)await syncCanonicalJobEvent(tx,jobId,businessId);return updated;});if(existing.type==="job"||event.type==="job"||existing.jobId||event.jobId)await recordAudit({actor:user,action:"CALENDAR_JOB_EVENT_UPDATED",entityType:"JobEvent",entityId:event.id,details:{businessId,previousJobId:existing.jobId,jobId:event.jobId}});return NextResponse.json(event);}catch{return NextResponse.json({error:"Update failed"},{status:400});}
}

export async function DELETE(_req:Request,{params}:{params:Promise<{id:string}>}){const a=await tenantActor();if("error" in a)return a.error;const{user,businessId}=a;const{id}=await params;const existing=await prisma.jobEvent.findFirst({where:{id,OR:[{job:{businessId}},{jobId:null,assignedTo:{businessId}}]},select:{id:true,jobId:true,type:true,assignedToId:true}});if(!existing)return NextResponse.json({error:"Event not found for this business"},{status:404});if(user.role==="EMPLOYEE"&&existing.assignedToId!==user.id)return NextResponse.json({error:"Forbidden"},{status:403});if(user.role==="EMPLOYEE"&&(existing.type==="job"||existing.jobId))return NextResponse.json({error:"Job schedule changes must be made by an admin or supervisor"},{status:403});try{await prisma.$transaction(async tx=>{await tx.jobEvent.delete({where:{id}});if(existing.type==="job"&&existing.jobId)await syncCanonicalJobEvent(tx,existing.jobId,businessId);});if(existing.type==="job"||existing.jobId)await recordAudit({actor:user,action:"CALENDAR_JOB_EVENT_DELETED",entityType:"JobEvent",entityId:existing.id,details:{businessId,jobId:existing.jobId}});return NextResponse.json({ok:true});}catch{return NextResponse.json({error:"Delete failed"},{status:400});}}
