"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { DEFAULT_MODULES, type YourPlanModule } from "@/lib/brand";

type Business={id:string;name:string;slug:string;industry:string|null;contactName:string|null;contactEmail:string|null;logoUrl:string|null;primaryColor:string;accentColor:string;modules:unknown;plan:string;monthlyPrice:number|null;active:boolean};
const UI={panel:"#07192b",border:"rgba(77,150,221,.24)",text:"#f5f9ff",mute:"#93a9c2",faint:"#617993",cyan:"#25c7ff",green:"#18d3a0"};
export default function BusinessPortalManager({businesses}:{businesses:Business[]}){
 const router=useRouter(); const [editing,setEditing]=useState<string|null>(null); const selected=useMemo(()=>businesses.find(b=>b.id===editing)??null,[businesses,editing]);
 return <section className="overflow-hidden rounded-xl" style={{background:UI.panel,border:`1px solid ${UI.border}`}}><div className="border-b px-5 py-4" style={{borderColor:UI.border}}><h2 className="text-sm font-semibold" style={{color:UI.text}}>Customer portals</h2><p className="mt-1 text-xs" style={{color:UI.faint}}>Manage branding, modules, subscription and customer access.</p></div>{businesses.length===0?<div className="px-5 py-12 text-center text-sm" style={{color:UI.mute}}>No customer businesses yet.</div>:<div className="divide-y" style={{borderColor:UI.border}}>{businesses.map(b=><div key={b.id} className="px-5 py-4" style={{borderColor:UI.border}}><div className="grid gap-3 md:grid-cols-[1.4fr_1fr_1fr_auto] md:items-center"><div><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full" style={{background:b.active?UI.green:UI.faint}}/><p className="font-semibold" style={{color:UI.text}}>{b.name}</p></div><p className="mt-1 text-xs" style={{color:UI.faint}}>{b.industry||"General business"} · /{b.slug}</p></div><div className="text-sm" style={{color:UI.text}}>{b.plan}</div><div className="text-sm" style={{color:UI.text}}>{Array.isArray(b.modules)?b.modules.length:0} modules</div><button onClick={()=>setEditing(editing===b.id?null:b.id)} className="rounded-lg px-3 py-2 text-xs font-semibold" style={{border:`1px solid ${UI.border}`,color:UI.cyan}}>{editing===b.id?"Close":"Manage"}</button></div>{selected?.id===b.id&&<Editor business={selected} onSaved={()=>{setEditing(null);router.refresh();}}/>}</div>)}</div>}</section>;
}
function Editor({business,onSaved}:{business:Business;onSaved:()=>void}){
 const initial=Array.isArray(business.modules)?business.modules.map(String) as YourPlanModule[]:[]; const [form,setForm]=useState({name:business.name,industry:business.industry??"",contactName:business.contactName??"",contactEmail:business.contactEmail??"",logoUrl:business.logoUrl??"",primaryColor:business.primaryColor,accentColor:business.accentColor,plan:business.plan,monthlyPrice:business.monthlyPrice?.toString()??"",active:business.active,modules:initial}); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 const toggle=(m:YourPlanModule)=>setForm(f=>({...f,modules:f.modules.includes(m)?f.modules.filter(x=>x!==m):[...f.modules,m]}));
 async function save(){if(!form.name.trim()||!form.contactEmail.trim()||form.modules.length===0)return setError("Name, contact email and at least one module are required.");setBusy(true);setError("");const res=await fetch(`/api/platform/businesses/${business.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.name.trim(),industry:form.industry.trim()||null,contactName:form.contactName.trim()||null,contactEmail:form.contactEmail.trim(),logoUrl:form.logoUrl.trim()||null,primaryColor:form.primaryColor,accentColor:form.accentColor,plan:form.plan.trim()||"CUSTOM",monthlyPrice:form.monthlyPrice===""?null:Number(form.monthlyPrice),active:form.active,modules:form.modules})});if(!res.ok){const j=await res.json().catch(()=>({}));setError(j.error||"Could not save customer settings.");setBusy(false);return;}setBusy(false);onSaved();}
 const input="w-full rounded-lg px-3 py-2 text-sm outline-none";
 return <div className="mt-4 rounded-xl p-4" style={{background:"#041525",border:`1px solid ${UI.border}`}}><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{[["Business name","name"],["Industry","industry"],["Owner / contact","contactName"],["Contact email","contactEmail"],["Logo URL","logoUrl"],["Plan","plan"],["Monthly $","monthlyPrice"]].map(([label,key])=><label key={key} className="text-xs" style={{color:UI.mute}}>{label}<input className={`${input} mt-1`} style={{background:"#07192b",border:`1px solid ${UI.border}`,color:UI.text}} value={String(form[key as keyof typeof form]??"")} onChange={e=>setForm(f=>({...f,[key]:e.target.value}))}/></label>)}<label className="text-xs" style={{color:UI.mute}}>Primary colour<input type="color" className="mt-1 h-10 w-full rounded-lg" value={form.primaryColor} onChange={e=>setForm(f=>({...f,primaryColor:e.target.value}))}/></label><label className="text-xs" style={{color:UI.mute}}>Accent colour<input type="color" className="mt-1 h-10 w-full rounded-lg" value={form.accentColor} onChange={e=>setForm(f=>({...f,accentColor:e.target.value}))}/></label></div><div className="mt-4"><p className="mb-2 text-xs font-semibold" style={{color:UI.mute}}>Enabled modules</p><div className="flex flex-wrap gap-2">{DEFAULT_MODULES.map(m=><button type="button" key={m} onClick={()=>toggle(m)} className="rounded-full px-3 py-1.5 text-xs" style={{background:form.modules.includes(m)?form.primaryColor:"transparent",border:`1px solid ${UI.border}`,color:form.modules.includes(m)?"white":UI.mute}}>{m}</button>)}</div></div><div className="mt-4 flex flex-wrap items-center gap-3"><label className="flex items-center gap-2 text-sm" style={{color:UI.text}}><input type="checkbox" checked={form.active} onChange={e=>setForm(f=>({...f,active:e.target.checked}))}/> Customer active</label><button disabled={busy} onClick={save} className="rounded-lg px-4 py-2 text-sm font-semibold text-white disabled:opacity-50" style={{background:form.primaryColor}}>{busy?"Saving…":"Save customer"}</button>{error&&<span className="text-xs text-rose-400">{error}</span>}</div></div>;
}
