import type { ReactNode } from "react";

export type DocumentLine={description:string;quantity:number;unitPrice:number;lineTotal:number;gstRate:number};
export function money(value:number){return new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD"}).format(value)}
export default function ElecplanDocument({kind,number,date,dueDate,clientName,clientEmail,address,lines,subtotal,gst,total,exclusions=[],children}:{kind:"QUOTE"|"TAX INVOICE";number:string;date:Date;dueDate?:Date|null;clientName:string;clientEmail?:string|null;address?:string|null;lines:DocumentLine[];subtotal:number;gst:number;total:number;exclusions?:string[];children?:ReactNode}){
 return <main className="mx-auto min-h-screen max-w-[900px] bg-white p-6 text-slate-900 print:max-w-none print:p-0 sm:p-10">
  <header className="flex items-start justify-between gap-6 border-b-4 border-sky-500 pb-7">
   <div><div className="flex h-14 w-14 items-center justify-center rounded-full bg-slate-950 text-xl font-black tracking-tight text-sky-400">EP</div><h1 className="mt-3 text-xl font-bold">ELECPLAN PTY LTD</h1><p className="text-xs text-slate-500">Electrical Contracting</p></div>
   <div className="text-right"><p className="text-3xl font-black tracking-tight">{kind}</p><p className="mt-2 text-sm font-semibold">{number}</p><p className="mt-1 text-xs text-slate-500">Date {date.toLocaleDateString("en-AU")}</p>{dueDate&&<p className="text-xs text-slate-500">Due {dueDate.toLocaleDateString("en-AU")}</p>}</div>
  </header>
  <section className="grid gap-6 py-7 sm:grid-cols-2"><div><p className="text-[10px] font-bold uppercase tracking-[.15em] text-sky-600">Bill to</p><p className="mt-2 font-bold">{clientName}</p>{clientEmail&&<p className="text-sm text-slate-600">{clientEmail}</p>}{address&&<p className="mt-1 text-sm text-slate-600">{address}</p>}</div><div className="sm:text-right"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-sky-600">Elecplan</p><p className="mt-2 text-sm font-semibold text-slate-800">Elecplan Pty Ltd</p><p className="text-sm text-slate-600">8 Seismic Ct, Rowville VIC 3178</p><p className="text-sm text-slate-600">Australia</p><p className="mt-1 text-sm text-slate-600">luke@elecplan.com.au · 0468 339 432</p><p className="mt-1 text-xs text-slate-500">ABN 94 691 392 720 · ACN 691 392 720</p></div></section>
  <table className="w-full border-collapse text-sm"><thead><tr className="bg-slate-950 text-left text-white"><th className="p-3">Description</th><th className="p-3 text-right">Qty</th><th className="p-3 text-right">Unit</th><th className="p-3 text-right">Amount</th></tr></thead><tbody>{lines.map((line,i)=><tr key={i} className="border-b border-slate-200"><td className="p-3">{line.description}</td><td className="p-3 text-right">{line.quantity}</td><td className="p-3 text-right">{money(line.unitPrice)}</td><td className="p-3 text-right font-semibold">{money(line.lineTotal)}</td></tr>)}</tbody></table>
  <div className="ml-auto mt-6 w-full max-w-xs space-y-2 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{money(subtotal)}</span></div><div className="flex justify-between"><span>GST</span><span>{money(gst)}</span></div><div className="flex justify-between border-t-2 border-slate-950 pt-3 text-xl font-black"><span>Total</span><span>{money(total)}</span></div></div>
  {exclusions.length>0&&<section className="mt-8 rounded-lg border border-amber-300 bg-amber-50 p-4"><h2 className="text-xs font-black uppercase tracking-[.12em] text-amber-800">Exclusions — not included</h2><ul className="mt-2 list-disc space-y-1 pl-5 text-sm">{exclusions.map((x,i)=><li key={i}>{x}</li>)}</ul></section>}
  {children}
  <footer className="mt-12 border-t border-slate-200 pt-5 text-xs text-slate-500"><p className="font-semibold text-slate-700">Thank you for choosing Elecplan.</p><p className="mt-1">This document was generated directly from the Elecplan portal.</p></footer>
 </main>
}