"use client";
import Link from"next/link";import{useState}from"react";import{Check,MessageCircle,ShieldCheck,UserCog,Users}from"lucide-react";
const g="#69be28",d="#080a0b",p="#111416",b="#2a3033",m="#9aa3a7";
type Person={role:string;access:string;scope:string;enabled:boolean};
const seed:Person[]=[
{role:"Team Manager",access:"Full access",scope:"Race weekends, riders, team, documents",enabled:true},
{role:"Mechanic · #100",access:"Rider crew",scope:"Brad West setup, notes and chat",enabled:true},
{role:"Mechanic · #111",access:"Rider crew",scope:"Dean Ferris setup, notes and chat",enabled:true},
{role:"Mechanic · #63",access:"Rider crew",scope:"Ryan Alexanderson setup, notes and chat",enabled:true},
{role:"Race Crew",access:"Event access",scope:"Schedule, equipment and team chat",enabled:true},
{role:"Media / Admin",access:"Restricted",scope:"Documents, communications and media",enabled:true}
];
export default function EmpireTeamDemoClient(){const[people,setPeople]=useState(seed);const[selected,setSelected]=useState(0);const person=people[selected];function toggle(i:number){setPeople(v=>v.map((x,j)=>j===i?{...x,enabled:!x.enabled}:x))}return <main className="min-h-screen text-white" style={{background:d}}><div className="mx-auto max-w-6xl p-4 md:p-6">
<section className="rounded-2xl border p-5 md:p-8" style={{background:"linear-gradient(125deg,#111416,#0b0d0e 70%,#15220e)",borderColor:b}}><div className="flex items-center gap-3"><Users style={{color:g}}/><div><p className="text-xs font-bold uppercase tracking-[.25em]" style={{color:g}}>Crew & access</p><h1 className="mt-1 text-3xl font-black uppercase md:text-4xl">Empire Team</h1></div></div><p className="mt-4 max-w-2xl text-sm leading-6" style={{color:m}}>Roles control what each person sees across rider records, crew chats, documents and race-day workflows.</p><div className="mt-5 grid grid-cols-3 gap-2"><div><p className="text-[9px] uppercase" style={{color:m}}>Crew roles</p><strong className="text-xl">{people.length}</strong></div><div><p className="text-[9px] uppercase" style={{color:m}}>Active</p><strong className="text-xl" style={{color:g}}>{people.filter(x=>x.enabled).length}</strong></div><div><p className="text-[9px] uppercase" style={{color:m}}>Access</p><strong className="text-xl" style={{color:g}}>Private</strong></div></div></section>
<section className="mt-5 grid gap-4 lg:grid-cols-[1fr_330px]"><div className="space-y-3">{people.map((x,i)=><article key={x.role} onClick={()=>setSelected(i)} className="cursor-pointer rounded-xl border p-4 md:grid md:grid-cols-[1fr_150px_1.4fr_auto] md:items-center md:gap-3 md:p-5" style={{background:p,borderColor:selected===i?g:b,opacity:x.enabled?1:.55}}><div className="flex items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg" style={{background:"rgba(105,190,40,.12)",color:g}}>{i===0?<ShieldCheck size={18}/>:<UserCog size={18}/>}</div><div><p className="font-bold">{x.role}</p><p className="mt-1 text-[10px] uppercase tracking-wider" style={{color:g}}>{x.access}</p></div></div><p className="mt-3 text-xs leading-5 md:mt-0" style={{color:m}}>{x.scope}</p><div className="mt-3 flex items-center justify-between border-t pt-3 md:mt-0 md:border-0 md:pt-0"><Link onClick={e=>e.stopPropagation()} href="/hq/demos/empire/chat" className="flex items-center gap-1 text-xs font-bold" style={{color:g}}><MessageCircle size={14}/>Chat</Link><button onClick={e=>{e.stopPropagation();toggle(i)}} className="rounded-lg border px-3 py-2 text-[10px] font-bold uppercase" style={{borderColor:x.enabled?g:b,color:x.enabled?g:m}}>{x.enabled?"Active":"Disabled"}</button></div></article>)}</div>
<aside className="h-fit rounded-xl border p-5" style={{background:p,borderColor:b}}><p className="text-[10px] font-bold uppercase tracking-widest" style={{color:g}}>Role preview</p><h2 className="mt-2 text-lg font-black">{person.role}</h2><p className="mt-2 text-xs leading-5" style={{color:m}}>{person.scope}</p><div className="mt-4 space-y-2">{["Race calendar","Team chat","Documents","Rider data","Bike setup"].map((x,i)=>{const allowed=person.access==="Full access"||person.access==="Rider crew"?(i!==2||person.access==="Full access"):person.access==="Event access"?i<2:([1,2].includes(i));return <div key={x} className="flex items-center justify-between rounded-lg border px-3 py-2 text-xs" style={{borderColor:b,color:allowed?"white":m}}><span>{x}</span>{allowed?<Check size={14} style={{color:g}}/>:<span className="text-[9px] uppercase">Hidden</span>}</div>})}</div><p className="mt-4 text-[10px] leading-5" style={{color:m}}>This interaction previews permission behavior only; it does not change any real customer or YourPlan account.</p></aside></section></div></main>}
