"use client";
import Link from"next/link";import{useMemo,useState}from"react";import{CheckCircle2,NotebookPen,Radio,Settings2,Wifi,Wrench,X}from"lucide-react";
const g="#69be28",d="#080a0b",p="#111416",b="#2a3033",m="#9aa3a7";
const sessions:{[key:string]:{p:string,n:string,name:string,best:string,last:string,gap:string,laps:string}[]}={
Practice:[{p:"P2",n:"100",name:"Brad West",best:"1:01.842",last:"1:02.115",gap:"+0.381",laps:"8"},{p:"P4",n:"111",name:"Dean Ferris",best:"1:02.104",last:"1:02.390",gap:"+0.643",laps:"9"},{p:"P7",n:"63",name:"Ryan Alexanderson",best:"1:02.771",last:"1:03.028",gap:"+1.310",laps:"8"}],
Qualifying:[{p:"P3",n:"111",name:"Dean Ferris",best:"1:00.884",last:"1:01.102",gap:"+0.512",laps:"10"},{p:"P5",n:"100",name:"Brad West",best:"1:01.106",last:"1:01.440",gap:"+0.734",laps:"9"},{p:"P8",n:"63",name:"Ryan Alexanderson",best:"1:01.805",last:"1:02.110",gap:"+1.433",laps:"9"}],
"Moto 1":[{p:"P2",n:"100",name:"Brad West",best:"1:01.504",last:"1:02.020",gap:"+0.267",laps:"12"},{p:"P6",n:"111",name:"Dean Ferris",best:"1:01.986",last:"1:02.331",gap:"+0.749",laps:"12"},{p:"P9",n:"63",name:"Ryan Alexanderson",best:"1:02.405",last:"1:02.900",gap:"+1.168",laps:"11"}]
};
export default function EmpireTimingsDemoClient(){const[session,setSession]=useState("Practice"),[rider,setRider]=useState("all"),[sourceOpen,setSourceOpen]=useState(false),[source,setSource]=useState("Preview data");const rows=useMemo(()=>sessions[session].filter(r=>rider==="all"||r.n===rider),[session,rider]);return <main className="min-h-screen text-white" style={{background:d}}><div className="mx-auto max-w-6xl p-4 md:p-6">
<section className="rounded-2xl border p-5 md:p-6" style={{background:"linear-gradient(125deg,#111416,#0b0d0e 70%,#15220e)",borderColor:b}}><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.25em]" style={{color:g}}>Empire timing centre</p><h1 className="mt-2 text-3xl font-black uppercase md:text-4xl">AUSX · {session}</h1><div className="mt-2 flex items-center gap-2 text-xs" style={{color:m}}><Wifi size={13} style={{color:g}}/>Townsville · {source}</div></div><div className="grid grid-cols-2 gap-2"><select value={rider} onChange={e=>setRider(e.target.value)} className="min-w-0 rounded-lg border px-3 py-2 text-xs text-white" style={{background:p,borderColor:b}}><option value="all">All riders</option><option value="100">#100 Brad West</option><option value="111">#111 Dean Ferris</option><option value="63">#63 Ryan Alexanderson</option></select><select value={session} onChange={e=>setSession(e.target.value)} className="min-w-0 rounded-lg border px-3 py-2 text-xs text-white" style={{background:p,borderColor:b}}>{Object.keys(sessions).map(x=><option key={x}>{x}</option>)}</select></div></div></section>
<section className="mt-4 rounded-xl border p-4 md:p-5" style={{background:p,borderColor:b}}><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div className="flex gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg" style={{background:"rgba(105,190,40,.12)",color:g}}><Radio size={19}/></div><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">AUSX Live Timing</h2><span className="rounded-full border px-2 py-0.5 text-[10px] font-bold uppercase tracking-widest" style={{borderColor:"rgba(105,190,40,.35)",color:g}}>Integration ready</span></div><p className="mt-1 text-xs leading-5" style={{color:m}}>Switch between session data and the integration-ready AUSX / Computime source.</p></div></div><button onClick={()=>setSourceOpen(true)} className="flex w-fit items-center gap-2 rounded-lg border px-3 py-2 text-xs" style={{borderColor:b}}><Settings2 size={15}/>Timing source</button></div></section>
<div className="mt-4 space-y-3 md:hidden">{rows.map(r=><article key={r.n} className="rounded-xl border p-4" style={{background:p,borderColor:b}}><div className="flex items-start justify-between"><div><span className="text-2xl font-black" style={{color:g}}>{r.p}</span><Link href={"/hq/demos/empire/riders/"+r.n} className="ml-3 font-bold">#{r.n} · {r.name}</Link></div><span className="text-xs" style={{color:m}}>{r.laps} laps</span></div><div className="mt-4 grid grid-cols-3 gap-2">{[["Best",r.best],["Last",r.last],["Gap",r.gap]].map(([a,v])=><div key={a}><p className="text-[9px] uppercase tracking-widest" style={{color:m}}>{a}</p><strong className="mt-1 block text-sm">{v}</strong></div>)}</div><div className="mt-4 flex gap-2"><Link href="/hq/demos/empire/notes" className="flex flex-1 items-center justify-center gap-1 rounded-lg border py-2 text-[10px]" style={{borderColor:b,color:m}}><NotebookPen size={13}/>Notes</Link><Link href="/hq/demos/empire/setup" className="flex flex-1 items-center justify-center gap-1 rounded-lg border py-2 text-[10px]" style={{borderColor:b,color:m}}><Wrench size={13}/>Setup</Link></div></article>)}</div>
<section className="mt-4 hidden overflow-hidden rounded-xl border md:block" style={{borderColor:b}}><div className="grid grid-cols-[70px_1fr_130px_130px_100px_70px] gap-2 border-b px-4 py-3 text-[10px] font-bold uppercase tracking-widest" style={{background:"#0c0f10",borderColor:b,color:m}}><span>Pos</span><span>Rider</span><span>Best</span><span>Last</span><span>Gap</span><span>Laps</span></div>{rows.map(r=><div key={r.n} className="grid grid-cols-[70px_1fr_130px_130px_100px_70px] gap-2 border-b px-4 py-4 text-sm" style={{background:p,borderColor:b}}><b style={{color:g}}>{r.p}</b><Link href={"/hq/demos/empire/riders/"+r.n} className="font-bold">#{r.n} · {r.name}</Link><span>{r.best}</span><span>{r.last}</span><span style={{color:m}}>{r.gap}</span><span style={{color:m}}>{r.laps}</span></div>)}</section>
<section className="mt-4 grid gap-3 sm:grid-cols-2"><Link href="/hq/demos/empire/notes" className="rounded-xl border p-4 text-sm font-bold" style={{background:p,borderColor:b}}>Race Notes <span style={{color:g}}>→</span><p className="mt-1 text-xs font-normal" style={{color:m}}>Capture rider feedback beside the session result.</p></Link><Link href="/hq/demos/empire/setup" className="rounded-xl border p-4 text-sm font-bold" style={{background:p,borderColor:b}}>Bike Setup <span style={{color:g}}>→</span><p className="mt-1 text-xs font-normal" style={{color:m}}>Compare setup changes against timing performance.</p></Link></section></div>
{sourceOpen&&<div className="fixed inset-0 z-[90] flex items-center justify-center bg-black/80 p-4"><div className="w-full max-w-md rounded-2xl border p-5" style={{background:p,borderColor:b}}><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-widest" style={{color:g}}>Timing source</p><h2 className="mt-1 text-xl font-black">Data connection</h2></div><button onClick={()=>setSourceOpen(false)} className="rounded-lg border p-2" style={{borderColor:b,color:m}}><X size={16}/></button></div>{["Preview data","AUSX / Computime ready"].map(x=><button key={x} onClick={()=>{setSource(x);setSourceOpen(false)}} className="mt-3 flex w-full items-center justify-between rounded-xl border p-4 text-left" style={{borderColor:source===x?g:b,color:source===x?g:"white"}}><span><strong className="text-sm">{x}</strong><span className="mt-1 block text-xs" style={{color:m}}>{x==="Preview data"?"Session data available without an external timing dependency.":"Mapped and ready for the supplied timing feed or API."}</span></span>{source===x&&<CheckCircle2 size={17}/>}</button>)}</div></div>}</main>}
