"use client";
import{useMemo,useState}from"react";
import Link from"next/link";
import{ArrowDown,ArrowLeft,ArrowUp,Check,Eye,GripVertical,LayoutDashboard,Monitor,Palette,Plus,Save,Settings2,ShieldCheck,Smartphone,Sparkles,ToggleLeft,ToggleRight,Trash2,Users}from"lucide-react";
import type{EmpireBuilderConfig,EmpireBuilderPage}from"@/lib/empire-builder";

const ui={bg:"#03101f",panel:"#07192b",panel2:"#04111f",border:"rgba(77,150,221,.24)",text:"#f5f9ff",muted:"#93a9c2",faint:"#617993",blue:"#168dff",cyan:"#25c7ff"};
type Tab="pages"|"branding"|"modules"|"access"|"preview";
export default function EmpirePortalBuilder({initial}:{initial:EmpireBuilderConfig}){
 const[cfg,setCfg]=useState(initial),[tab,setTab]=useState<Tab>("pages"),[device,setDevice]=useState<"desktop"|"mobile">("desktop"),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[dirty,setDirty]=useState(false);
 const enabled=useMemo(()=>cfg.pages.filter(p=>p.enabled),[cfg.pages]);
 function mutate(next:EmpireBuilderConfig){setCfg(next);setDirty(true);setMessage("")}
 function patch(p:Partial<EmpireBuilderConfig>){mutate({...cfg,...p})}
 function move(index:number,delta:number){const to=index+delta;if(to<0||to>=cfg.pages.length)return;const pages=[...cfg.pages];[pages[index],pages[to]]=[pages[to],pages[index]];patch({pages})}
 function updatePage(id:string,p:Partial<EmpireBuilderPage>){patch({pages:cfg.pages.map(x=>x.id===id?{...x,...p}:x)})}
 function addPage(){const id=`custom-${Date.now()}`;patch({pages:[...cfg.pages,{id,label:"New page",slug:`page-${cfg.pages.filter(x=>x.kind==="custom").length+1}`,group:"Custom",enabled:true,kind:"custom"}]})}
 function removePage(id:string){patch({pages:cfg.pages.filter(x=>x.id!==id)})}
 async function save(publish=false){setBusy(true);setMessage(publish?"Publishing portal…":"Saving draft…");try{const r=await fetch("/api/platform/demo-builder/empire",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({config:cfg,publish})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Save failed");setCfg(data.config);setDirty(false);setMessage(publish?"Published. Empire portal configuration is live.":"Draft saved.")}catch(e){setMessage(e instanceof Error?e.message:"Save failed")}finally{setBusy(false)}}
 const tabs:[Tab,string,any][]=[["pages","Pages & navigation",LayoutDashboard],["branding","Branding",Palette],["modules","Features",Settings2],["access","Access",Users],["preview","Preview",Eye]];
 return <main className="min-h-screen" style={{background:ui.bg,color:ui.text}}>
  <div className="sticky top-0 z-30 border-b backdrop-blur-xl" style={{borderColor:ui.border,background:"rgba(3,16,31,.94)"}}><div className="mx-auto flex max-w-[1600px] flex-wrap items-center justify-between gap-3 px-4 py-3 md:px-6"><div className="flex min-w-0 items-center gap-3"><Link href="/hq/demos" className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border" style={{borderColor:ui.border,color:ui.muted}}><ArrowLeft size={18}/></Link><div className="min-w-0"><div className="flex items-center gap-2"><span className="rounded-md px-2 py-1 text-[9px] font-black uppercase tracking-[.18em]" style={{background:"rgba(105,190,40,.12)",color:"#8fe35c"}}>Portal Builder</span>{dirty&&<span className="text-[10px]" style={{color:ui.faint}}>Unsaved changes</span>}</div><h1 className="mt-1 truncate text-lg font-bold">Empire HQ</h1></div></div><div className="flex items-center gap-2"><Link href="/hq/demos/empire" target="_blank" className="hidden rounded-lg border px-3 py-2 text-xs font-semibold sm:block" style={{borderColor:ui.border,color:ui.muted}}>Open portal ↗</Link><button disabled={busy} onClick={()=>save(false)} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-semibold disabled:opacity-50" style={{borderColor:ui.border}}><Save size={14}/>Save draft</button><button disabled={busy} onClick={()=>save(true)} className="flex items-center gap-2 rounded-lg px-4 py-2 text-xs font-black disabled:opacity-50" style={{background:"#69be28",color:"#071007"}}><Check size={14}/>Publish</button></div></div></div>
  <div className="mx-auto grid max-w-[1600px] gap-4 p-4 md:p-6 xl:grid-cols-[250px_1fr]">
   <aside className="h-fit rounded-2xl border p-3 xl:sticky xl:top-24" style={{background:ui.panel,borderColor:ui.border}}><div className="mb-3 rounded-xl p-4" style={{background:ui.panel2}}><p className="text-[10px] font-bold uppercase tracking-[.2em]" style={{color:"#69be28"}}>Motorsport client</p><p className="mt-2 font-bold">Penrite Racing Empire Kawasaki</p><p className="mt-1 text-xs" style={{color:ui.faint}}>Changes here apply to Empire only.</p></div>{tabs.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className="mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-semibold" style={{background:tab===id?ui.blue:"transparent",color:tab===id?"white":ui.muted}}><Icon size={17}/>{label}</button>)}<div className="mt-4 border-t pt-4 text-[11px] leading-5" style={{borderColor:ui.border,color:ui.faint}}><ShieldCheck size={15} className="mb-2" style={{color:ui.cyan}}/>Tenant-isolated configuration. Other client portals are not modified by these controls.</div></aside>
   <section className="min-w-0">
    <div className="mb-4 flex flex-col justify-between gap-3 rounded-2xl border p-5 sm:flex-row sm:items-center" style={{background:ui.panel,borderColor:ui.border}}><div><p className="text-[10px] font-bold uppercase tracking-[.2em]" style={{color:ui.cyan}}>Build without code</p><h2 className="mt-2 text-2xl font-bold">{tabs.find(x=>x[0]===tab)?.[1]}</h2><p className="mt-1 text-sm" style={{color:ui.muted}}>{tab==="pages"?"Turn pages on or off, rename them and control the menu order.":tab==="branding"?"Control the Empire portal identity and race-team colour system.":tab==="modules"?"Choose the operational features available inside Empire HQ.":tab==="access"?"Define what each Empire role can see and edit.":"See the portal composition before you publish."}</p></div>{message&&<div className="rounded-xl border px-3 py-2 text-xs" style={{borderColor:ui.border,color:message.includes("failed")? "#fca5a5":"#8fe35c"}}>{message}</div>}</div>
    {tab==="pages"&&<Pages cfg={cfg} updatePage={updatePage} move={move} addPage={addPage} removePage={removePage}/>}
    {tab==="branding"&&<Branding cfg={cfg} mutate={mutate}/>}
    {tab==="modules"&&<Modules cfg={cfg} mutate={mutate}/>}
    {tab==="access"&&<Access cfg={cfg}/>}
    {tab==="preview"&&<Preview cfg={cfg} pages={enabled} device={device} setDevice={setDevice}/>}
   </section>
  </div>
 </main>
}
function Card({children}:{children:React.ReactNode}){return <div className="rounded-2xl border p-5" style={{background:ui.panel,borderColor:ui.border}}>{children}</div>}
function Pages({cfg,updatePage,move,addPage,removePage}:{cfg:EmpireBuilderConfig;updatePage:(id:string,p:Partial<EmpireBuilderPage>)=>void;move:(i:number,d:number)=>void;addPage:()=>void;removePage:(id:string)=>void}){return <Card><div className="flex items-center justify-between"><div><h3 className="font-bold">Portal navigation</h3><p className="mt-1 text-xs" style={{color:ui.faint}}>Order shown here becomes the Empire menu order.</p></div><button onClick={addPage} className="flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-bold" style={{background:ui.blue}}><Plus size={14}/>Add page</button></div><div className="mt-5 space-y-2">{cfg.pages.map((p,i)=><div key={p.id} className="grid gap-3 rounded-xl border p-3 md:grid-cols-[32px_1.2fr_.9fr_.7fr_auto] md:items-center" style={{background:ui.panel2,borderColor:ui.border}}><GripVertical size={16} style={{color:ui.faint}}/><input value={p.label} onChange={e=>updatePage(p.id,{label:e.target.value})} className="h-10 rounded-lg border bg-transparent px-3 text-sm outline-none" style={{borderColor:ui.border}}/><input value={p.group} onChange={e=>updatePage(p.id,{group:e.target.value})} className="h-10 rounded-lg border bg-transparent px-3 text-xs outline-none" style={{borderColor:ui.border,color:ui.muted}}/><div className="text-xs" style={{color:ui.faint}}>{p.kind==="custom"?<input value={p.slug} onChange={e=>updatePage(p.id,{slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"")})} className="h-10 w-full rounded-lg border bg-transparent px-3" style={{borderColor:ui.border}}/>:`/${p.slug||"dashboard"}`}</div><div className="flex items-center justify-end gap-1"><button onClick={()=>move(i,-1)} className="p-2" aria-label="Move up"><ArrowUp size={15}/></button><button onClick={()=>move(i,1)} className="p-2" aria-label="Move down"><ArrowDown size={15}/></button><button onClick={()=>updatePage(p.id,{enabled:!p.enabled})} className="p-2" aria-label="Toggle page">{p.enabled?<ToggleRight size={24} style={{color:"#69be28"}}/>:<ToggleLeft size={24} style={{color:ui.faint}}/>}</button>{p.kind==="custom"&&<button onClick={()=>removePage(p.id)} className="p-2 text-red-300" aria-label="Delete page"><Trash2 size={15}/></button>}</div></div>)}</div></Card>}
function Branding({cfg,mutate}:{cfg:EmpireBuilderConfig;mutate:(c:EmpireBuilderConfig)=>void}){const t=cfg.theme;const colour=(key:keyof typeof t,label:string)=><label className="text-xs" style={{color:ui.muted}}>{label}<div className="mt-2 flex gap-2"><input type="color" value={t[key]} onChange={e=>mutate({...cfg,theme:{...t,[key]:e.target.value}})} className="h-11 w-12 rounded bg-transparent"/><input value={t[key]} onChange={e=>mutate({...cfg,theme:{...t,[key]:e.target.value}})} className="h-11 min-w-0 flex-1 rounded-lg border bg-transparent px-3 text-sm" style={{borderColor:ui.border}}/></div></label>;return <div className="grid gap-4"><Card><h3 className="font-bold">Portal identity</h3><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-xs" style={{color:ui.muted}}>Portal name<input value={cfg.portalName} onChange={e=>mutate({...cfg,portalName:e.target.value})} className="mt-2 h-11 w-full rounded-lg border bg-transparent px-3 text-sm text-white" style={{borderColor:ui.border}}/></label><label className="text-xs" style={{color:ui.muted}}>Portal subtitle<input value={cfg.portalSubtitle} onChange={e=>mutate({...cfg,portalSubtitle:e.target.value})} className="mt-2 h-11 w-full rounded-lg border bg-transparent px-3 text-sm text-white" style={{borderColor:ui.border}}/></label></div></Card><Card><h3 className="font-bold">Race-team theme</h3><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[colour("accent","Accent"),colour("background","Background"),colour("panel","Panels"),colour("border","Borders")]}</div><div className="mt-5 rounded-2xl border p-5" style={{background:t.background,borderColor:t.border}}><p className="text-[10px] font-black uppercase tracking-[.24em]" style={{color:t.accent}}>Live colour sample</p><div className="mt-3 rounded-xl border p-4" style={{background:t.panel,borderColor:t.border}}><div className="h-2 w-28 rounded" style={{background:t.accent}}/><p className="mt-4 font-bold">{cfg.portalName}</p><p className="mt-1 text-xs text-white/50">{cfg.portalSubtitle}</p></div></div></Card><Card><div className="flex items-center gap-3"><Palette style={{color:ui.cyan}}/><div><h3 className="font-bold">Logo & artwork positioning</h3><p className="mt-1 text-xs" style={{color:ui.muted}}>The existing YourPlan branding editor already handles desktop, mobile, sign-in, app icon and artwork positioning. This builder now owns the portal structure; artwork controls remain available from Customer Portals.</p></div></div><Link href="/hq/portals" className="mt-4 inline-flex rounded-lg border px-3 py-2 text-xs font-semibold" style={{borderColor:ui.border,color:ui.cyan}}>Open customer branding manager →</Link></Card></div>}
function Modules({cfg,mutate}:{cfg:EmpireBuilderConfig;mutate:(c:EmpireBuilderConfig)=>void}){return <Card><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{cfg.modules.map(x=><button key={x.id} onClick={()=>mutate({...cfg,modules:cfg.modules.map(m=>m.id===x.id?{...m,enabled:!m.enabled}:m)})} className="flex items-center justify-between rounded-xl border p-4 text-left" style={{background:ui.panel2,borderColor:x.enabled?"rgba(105,190,40,.45)":ui.border}}><div><p className="text-sm font-semibold">{x.label}</p><p className="mt-1 text-[11px]" style={{color:ui.faint}}>{x.enabled?"Enabled in Empire HQ":"Disabled"}</p></div>{x.enabled?<ToggleRight size={27} style={{color:"#69be28"}}/>:<ToggleLeft size={27} style={{color:ui.faint}}/>}</button>)}</div></Card>}
function Access({cfg}:{cfg:EmpireBuilderConfig}){return <Card><div className="grid gap-3 lg:grid-cols-3">{cfg.roles.map(r=><div key={r.id} className="rounded-xl border p-4" style={{background:ui.panel2,borderColor:ui.border}}><div className="flex items-center gap-2"><ShieldCheck size={17} style={{color:ui.cyan}}/><h3 className="font-bold">{r.label}</h3></div><p className="mt-3 text-xs" style={{color:ui.muted}}>{r.view.length} visible sections · {r.edit.length} editable sections</p><div className="mt-4 flex flex-wrap gap-1">{r.edit.slice(0,6).map(x=><span key={x} className="rounded-md px-2 py-1 text-[10px]" style={{background:"rgba(37,199,255,.08)",color:ui.cyan}}>{x}</span>)}</div></div>)}</div><p className="mt-4 text-xs" style={{color:ui.faint}}>Role matrices are stored with the Empire portal configuration. Fine-grained user assignment is the next layer on top of these roles.</p></Card>}
function Preview({cfg,pages,device,setDevice}:{cfg:EmpireBuilderConfig;pages:EmpireBuilderPage[];device:"desktop"|"mobile";setDevice:(d:"desktop"|"mobile")=>void}){const groups=[...new Set(pages.map(p=>p.group))];return <Card><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold">Portal preview</h3><p className="mt-1 text-xs" style={{color:ui.faint}}>Preview the menu structure and theme before publishing.</p></div><div className="flex rounded-lg border p-1" style={{borderColor:ui.border,background:ui.panel2}}><button onClick={()=>setDevice("desktop")} className="flex items-center gap-2 rounded-md px-3 py-2 text-xs" style={{background:device==="desktop"?ui.blue:"transparent"}}><Monitor size={14}/>Desktop</button><button onClick={()=>setDevice("mobile")} className="flex items-center gap-2 rounded-md px-3 py-2 text-xs" style={{background:device==="mobile"?ui.blue:"transparent"}}><Smartphone size={14}/>Mobile</button></div></div><div className={`mx-auto mt-5 overflow-hidden rounded-2xl border shadow-2xl ${device==="mobile"?"max-w-[390px]":""}`} style={{background:cfg.theme.background,borderColor:cfg.theme.border}}>{device==="desktop"?<div className="flex h-[620px]"><PreviewNav cfg={cfg} groups={groups} pages={pages}/><PreviewBody cfg={cfg}/></div>:<div className="min-h-[680px]"><div className="flex h-16 items-center justify-between border-b px-4" style={{background:cfg.theme.panel,borderColor:cfg.theme.border}}><div className="h-9 w-9 rounded-lg border" style={{borderColor:cfg.theme.border}}/><b>{cfg.portalName}</b><div className="h-9 w-9 rounded-full border" style={{borderColor:cfg.theme.border}}/></div><div className="w-[78%] border-r p-4" style={{background:cfg.theme.panel,borderColor:cfg.theme.border}}><PreviewNavContent cfg={cfg} groups={groups} pages={pages}/></div></div>}</div></Card>}
function PreviewNav({cfg,groups,pages}:{cfg:EmpireBuilderConfig;groups:string[];pages:EmpireBuilderPage[]}){return <aside className="w-[235px] shrink-0 border-r p-4" style={{background:cfg.theme.panel,borderColor:cfg.theme.border}}><PreviewNavContent cfg={cfg} groups={groups} pages={pages}/></aside>}
function PreviewNavContent({cfg,groups,pages}:{cfg:EmpireBuilderConfig;groups:string[];pages:EmpireBuilderPage[]}){return <><div className="mb-6 rounded-xl border p-3 text-center" style={{borderColor:cfg.theme.border}}><p className="text-[10px] font-black uppercase tracking-[.2em]" style={{color:cfg.theme.accent}}>Empire Motorsports</p><p className="mt-1 text-sm font-bold">{cfg.portalName}</p></div>{groups.map(g=><div key={g} className="mb-4"><p className="mb-1 px-2 text-[9px] font-black uppercase tracking-[.18em] text-white/35">{g}</p>{pages.filter(p=>p.group===g).map((p,i)=><div key={p.id} className="mb-1 rounded-lg px-3 py-2 text-xs font-semibold" style={{background:p.id==="dashboard"?cfg.theme.accent:"transparent",color:p.id==="dashboard"?"#061006":"rgba(255,255,255,.65)"}}>{p.label}</div>)}</div>)}</>}
function PreviewBody({cfg}:{cfg:EmpireBuilderConfig}){return <div className="min-w-0 flex-1 p-6"><p className="text-[10px] font-black uppercase tracking-[.22em]" style={{color:cfg.theme.accent}}>Factory race operations</p><h2 className="mt-2 text-3xl font-black uppercase">{cfg.portalName}</h2><p className="mt-2 text-sm text-white/45">{cfg.portalSubtitle}</p><div className="mt-6 grid grid-cols-3 gap-3">{["Next race","Riders","Bikes ready"].map((x,i)=><div key={x} className="rounded-xl border p-4" style={{background:cfg.theme.panel,borderColor:cfg.theme.border}}><p className="text-[9px] uppercase text-white/35">{x}</p><p className="mt-2 font-bold">{i===0?"AUSX":i===1?"3":"3/3"}</p></div>)}</div><div className="mt-4 rounded-2xl border p-5" style={{background:cfg.theme.panel,borderColor:cfg.theme.border}}><Sparkles size={18} style={{color:cfg.theme.accent}}/><div className="mt-4 h-3 w-2/3 rounded bg-white/10"/><div className="mt-3 h-20 rounded-xl bg-black/20"/></div></div>}
