"use client";
import Link from"next/link";import{useState}from"react";import{CalendarDays,CheckCircle2,Clock3,Flag,MessageCircle,Wrench}from"lucide-react";
const g="#69be28",d="#080a0b",p="#111416",b="#2a3033",m="#9aa3a7";
const riders=[["100","Brad West","Practice setup saved"],["111","Dean Ferris","Tyres checked"],["63","Ryan Alexanderson","Shock note open"]];
const seed=[{name:"Rider briefing confirmed",done:true},{name:"#100 front-end check",done:false},{name:"#63 rear suspension follow-up",done:false},{name:"Timing / comms gear",done:true},{name:"Event documents loaded",done:true}];
export default function EmpireOverviewDemoClient(){const[tasks,setTasks]=useState(seed);function toggle(i:number){setTasks(v=>v.map((x,j)=>j===i?{...x,done:!x.done}:x))}const done=tasks.filter(x=>x.done).length;const readiness=Math.round(done/tasks.length*100);return <main className="min-h-screen text-white" style={{background:d}}><div className="mx-auto max-w-7xl p-4 md:p-6"><section className="rounded-2xl border p-6 md:p-8" style={{background:"linear-gradient(125deg,#111416,#0b0d0e 70%,#15220e)",borderColor:b}}><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.25em]" style={{color:g}}>Next event · AUSX Round 1</p><h1 className="mt-2 text-3xl font-black uppercase md:text-5xl">Team Operations</h1><p className="mt-3 text-sm" style={{color:m}}>Townsville · 3 October 2026 · Empire race-weekend readiness</p></div><div className="rounded-xl border px-5 py-3 text-right" style={{borderColor:b,background:"#0c0f10"}}><p className="text-[9px] font-bold uppercase tracking-widest" style={{color:m}}>Readiness</p><p className="mt-1 text-3xl font-black" style={{color:g}}>{readiness}%</p></div></div></section>
<section className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Next session","Practice · 09:15",Clock3],["Riders ready","3 / 3",Flag],["Open actions",String(tasks.length-done),Wrench],["Team channels","5 active",MessageCircle]].map(([a,v,I]:any)=><div key={a} className="rounded-xl border p-4" style={{background:p,borderColor:b}}><I size={17} style={{color:g}}/><p className="mt-3 text-[10px] font-bold uppercase tracking-widest" style={{color:m}}>{a}</p><p className="mt-1 text-lg font-black">{v}</p></div>)}</section>
<section className="mt-4 grid gap-4 lg:grid-cols-[1.05fr_.75fr_.8fr]"><div className="rounded-xl border p-5" style={{background:p,borderColor:b}}><div className="flex items-center justify-between"><h2 className="font-bold">Rider readiness</h2><Link href="/hq/demos/empire/riders" className="text-xs font-bold" style={{color:g}}>All riders →</Link></div>{riders.map(([n,name,note])=><Link href={"/hq/demos/empire/riders/"+n} key={n} className="mt-3 grid grid-cols-[60px_1fr_auto] items-center gap-3 rounded-lg border p-3" style={{borderColor:b}}><span className="text-xl font-black italic" style={{color:g}}>#{n}</span><div><p className="text-sm font-bold">{name}</p><p className="mt-1 text-xs" style={{color:m}}>{note}</p></div><span className="text-xs font-bold" style={{color:g}}>Ready</span></Link>)}</div>
<div className="rounded-xl border p-5" style={{background:p,borderColor:b}}><div className="flex items-center gap-2"><CheckCircle2 size={17} style={{color:g}}/><h2 className="font-bold">Readiness actions</h2></div><p className="mt-2 text-[10px]" style={{color:m}}>Tap an item to update the presentation state.</p>{tasks.map((x,i)=><button onClick={()=>toggle(i)} key={x.name} className="mt-3 flex w-full items-center justify-between gap-3 rounded-lg border p-3 text-left" style={{borderColor:x.done?g:b}}><span className="text-xs">{x.name}</span><span className="text-[9px] font-bold uppercase" style={{color:x.done?g:m}}>{x.done?"Ready":"Open"}</span></button>)}</div>
<aside className="rounded-xl border p-5" style={{background:p,borderColor:b}}><div className="flex items-center gap-2"><CalendarDays size={17} style={{color:g}}/><h2 className="font-bold">Quick race-day access</h2></div>{[["Race weekend","/hq/demos/empire/weekend"],["Live timings","/hq/demos/empire/timings"],["Race notes","/hq/demos/empire/notes"],["Bike setup","/hq/demos/empire/setup"],["Workshop","/hq/demos/empire/workshop"],["Parts & inventory","/hq/demos/empire/parts"],["Team chat","/hq/demos/empire/chat"]].map(([x,h])=><Link href={h} key={x} className="mt-3 flex items-center justify-between rounded-lg border p-3 text-sm font-semibold" style={{borderColor:b}}><span>{x}</span><span style={{color:g}}>→</span></Link>)}</aside></section></div></main>}
