"use client";

import { useEffect, useMemo, useState } from "react";
import { Camera, CheckCircle2, Clock3, MapPin, Navigation, RotateCcw, X } from "lucide-react";

type Workflow = {
  job: { id:string; title:string; address:string; notes:string|null; status:string; scheduledStart:string|null; scheduledEnd:string|null; client:{name:string;contactName:string|null;phone:string|null} };
  activeArrival: string|null;
  elapsedSeconds: number;
};

const UI={panel:"#07192b",alt:"#09213a",border:"rgba(77,150,221,.24)",text:"#f5f9ff",mute:"#93a9c2",cyan:"#25c7ff",blue:"#168dff",green:"#18d3a0",orange:"#ff9f1c",red:"#ff5e72"};

export default function FieldJobModal({jobId,onClose,onDone}:{jobId:string;onClose:()=>void;onDone:()=>void}){
 const[data,setData]=useState<Workflow|null>(null);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[mode,setMode]=useState<"complete"|"revisit"|null>(null);const[text,setText]=useState("");const[now,setNow]=useState(Date.now());const[photos,setPhotos]=useState<File[]>([]);
 async function load(){setLoading(true);const r=await fetch(`/api/jobs/${jobId}/workflow`,{cache:"no-store"});const b=await r.json().catch(()=>null);setLoading(false);if(!r.ok){setError(b?.error??"Could not open job");return;}setData(b);}
 useEffect(()=>{load();},[jobId]);useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t);},[]);
 const elapsed=useMemo(()=>{if(!data?.activeArrival)return 0;return Math.max(0,Math.floor((now-new Date(data.activeArrival).getTime())/1000));},[data?.activeArrival,now]);
 function duration(s:number){const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;return h?`${h}h ${String(m).padStart(2,"0")}m ${String(sec).padStart(2,"0")}s`:`${m}m ${String(sec).padStart(2,"0")}s`;}
 async function action(payload:object){setBusy(true);setError(null);const r=await fetch(`/api/jobs/${jobId}/workflow`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const b=await r.json().catch(()=>null);setBusy(false);if(!r.ok){setError(b?.error??"Could not update job");return false;}return true;}
 async function uploadPhotos(){for(const file of photos){const ticket=await fetch("/api/storage/upload-ticket",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"project-photos",fileName:file.name,contentType:file.type,sizeBytes:file.size})});const t=await ticket.json().catch(()=>null);if(!ticket.ok)throw new Error(t?.error??"Could not prepare photo upload");const put=await fetch(t.uploadUrl,{method:"PUT",headers:t.uploadHeaders,body:file});if(!put.ok)throw new Error("Photo upload failed");const save=await fetch("/api/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({jobId,commitToken:t.commitToken})});if(!save.ok){const b=await save.json().catch(()=>null);throw new Error(b?.error??"Could not save photo");}}}
 async function arrive(){if(await action({action:"ARRIVE"})){await load();onDone();}}
 async function closeVisit(){if(mode==="revisit"&&!text.trim()){setError("Enter why this job needs a revisit.");return;}setBusy(true);setError(null);try{if(photos.length)await uploadPhotos();}catch(e){setBusy(false);setError(e instanceof Error?e.message:"Could not upload photos");return;}setBusy(false);const ok=await action(mode==="revisit"?{action:"REVISIT",reason:text.trim()}:{action:"COMPLETE",notes:text.trim()||null});if(ok){onDone();onClose();}}
 if(loading)return <Shell onClose={onClose}><p style={{color:UI.mute}}>Loading job…</p></Shell>;if(!data)return <Shell onClose={onClose}><p style={{color:UI.red}}>{error??"Could not open job"}</p></Shell>;
 const j=data.job;const active=Boolean(data.activeArrival);const maps=`https://maps.apple.com/?q=${encodeURIComponent(j.address)}`;
 return <Shell onClose={onClose}><div className="space-y-4"><div><p className="text-xs font-semibold uppercase tracking-[.12em]" style={{color:UI.cyan}}>Field job</p><h2 className="mt-1 text-xl font-bold" style={{color:UI.text}}>{j.title}</h2><p className="mt-1 text-sm" style={{color:UI.mute}}>{j.client.name}</p></div><a href={maps} target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-xl p-3" style={{background:UI.alt,border:`1px solid ${UI.border}`,color:UI.text}}><MapPin size={18} style={{color:UI.cyan}}/><span className="min-w-0 flex-1 text-sm">{j.address}</span><Navigation size={17} style={{color:UI.cyan}}/></a>{j.notes&&<div className="rounded-xl p-3 text-sm leading-6" style={{background:UI.alt,border:`1px solid ${UI.border}`,color:UI.mute}}>{j.notes}</div>}
 {active?<div className="rounded-2xl p-4 text-center" style={{background:"rgba(24,211,160,.08)",border:"1px solid rgba(24,211,160,.3)"}}><Clock3 size={22} className="mx-auto" style={{color:UI.green}}/><p className="mt-2 text-xs font-semibold uppercase tracking-[.12em]" style={{color:UI.green}}>On site</p><p className="mt-1 text-3xl font-bold tabular-nums" style={{color:UI.text}}>{duration(elapsed)}</p><p className="mt-1 text-xs" style={{color:UI.mute}}>Timer started when Arrived was pressed</p></div>:j.status!=="COMPLETE"?<button type="button" disabled={busy} onClick={arrive} className="w-full rounded-xl py-4 text-base font-bold disabled:opacity-60" style={{background:UI.green,color:"#03101f"}}>I’ve arrived — start timer</button>:<div className="rounded-xl p-4 text-center font-semibold" style={{background:"rgba(24,211,160,.08)",border:"1px solid rgba(24,211,160,.25)",color:UI.green}}>Job complete</div>}
 {active&&!mode&&<div className="grid grid-cols-2 gap-2"><button onClick={()=>setMode("revisit")} className="rounded-xl py-3 font-semibold" style={{background:"rgba(255,159,28,.08)",border:"1px solid rgba(255,159,28,.3)",color:UI.orange}}><RotateCcw size={16} className="mr-2 inline"/>Revisit</button><button onClick={()=>setMode("complete")} className="rounded-xl py-3 font-semibold" style={{background:UI.blue,color:"white"}}><CheckCircle2 size={16} className="mr-2 inline"/>Finish job</button></div>}
 {mode&&<div className="space-y-3 rounded-xl p-3" style={{background:UI.alt,border:`1px solid ${UI.border}`}}><p className="text-sm font-semibold" style={{color:UI.text}}>{mode==="revisit"?"Why does this job need a revisit?":"Finish this job"}</p><textarea value={text} onChange={e=>setText(e.target.value)} rows={3} placeholder={mode==="revisit"?"e.g. Waiting on parts, return with another electrician…":"Completion notes (optional)"} className="w-full rounded-lg p-3 text-sm outline-none" style={{background:"#041323",border:`1px solid ${UI.border}`,color:UI.text}}/><label className="flex cursor-pointer items-center justify-center gap-2 rounded-lg px-3 py-3 text-sm font-semibold" style={{background:"#041323",border:`1px solid ${UI.border}`,color:UI.cyan}}><Camera size={16}/>Add photos<input type="file" accept="image/jpeg,image/png,image/webp" multiple capture="environment" className="hidden" onChange={e=>setPhotos(Array.from(e.target.files??[]))}/></label>{photos.length>0&&<p className="text-xs" style={{color:UI.mute}}>{photos.length} photo{photos.length===1?"":"s"} ready to upload</p>}<div className="grid grid-cols-2 gap-2"><button onClick={()=>{setMode(null);setText("");setPhotos([])}} className="rounded-lg py-3 text-sm font-semibold" style={{color:UI.mute,border:`1px solid ${UI.border}`}}>Back</button><button disabled={busy} onClick={closeVisit} className="rounded-lg py-3 text-sm font-bold disabled:opacity-60" style={{background:mode==="revisit"?UI.orange:UI.green,color:"#03101f"}}>{busy?"Saving…":mode==="revisit"?"Save revisit":"Complete job"}</button></div></div>}
 {error&&<p className="rounded-lg p-3 text-sm" style={{background:"rgba(255,94,114,.08)",color:UI.red}}>{error}</p>}</div></Shell>;
}
function Shell({children,onClose}:{children:React.ReactNode;onClose:()=>void}){return <div className="fixed inset-0 z-[70] flex items-end justify-center bg-black/70 backdrop-blur-sm md:items-center md:p-4" onClick={onClose}><section className="max-h-[92vh] w-full max-w-lg overflow-auto rounded-t-2xl p-5 md:rounded-2xl" style={{background:UI.panel,border:`1px solid ${UI.border}`}} onClick={e=>e.stopPropagation()}><div className="mb-3 flex justify-end"><button onClick={onClose} aria-label="Close" style={{color:UI.mute}}><X size={20}/></button></div>{children}</section></div>}
