"use client";
import {useMemo,useState}from"react";
import{useRouter}from"next/navigation";
import{Camera,ImageIcon,Minus,PackageSearch,Plus,Search,X}from"lucide-react";
import TopBar from"@/components/TopBar";

export type StockRow={id:string;name:string;unit:string;onHand:number;parLevel:number;supplier:string|null;hasPhoto:boolean};
const UI={panel:"var(--brand-panel, #07192b)",panelAlt:"var(--brand-panel-alt, #09213a)",border:"var(--brand-border, rgba(77,150,221,.24))",borderSoft:"var(--brand-border-soft, rgba(77,150,221,.12))",text:"#f5f9ff",mute:"var(--brand-muted, #93a9c2)",faint:"var(--brand-faint, #617993)",blue:"var(--brand-primary, #168dff)",cyan:"var(--brand-accent, #25c7ff)",red:"#ff5e72"};

async function upload(file:File){const r=await fetch("/api/storage/upload-ticket",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind:"material-photos",fileName:file.name,contentType:file.type,sizeBytes:file.size})});const t=await r.json();if(!r.ok)throw new Error(t.error||"Could not prepare photo");const put=await fetch(t.uploadUrl,{method:"PUT",headers:t.uploadHeaders,body:file});if(!put.ok)throw new Error("Could not upload photo");return t.commitToken as string}

export default function MaterialsView({items}:{items:StockRow[]}){
  const router=useRouter();
  const[showNew,setShowNew]=useState(false),[busy,setBusy]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[query,setQuery]=useState(""),[photoOpen,setPhotoOpen]=useState<StockRow|null>(null);
  const stocked=useMemo(()=>items.filter(i=>i.onHand>0),[items]);
  const filtered=useMemo(()=>{const n=query.trim().toLowerCase();return n?stocked.filter(i=>[i.name,i.unit,i.supplier??""].join(" ").toLowerCase().includes(n)):stocked},[stocked,query]);
  async function update(item:StockRow,delta:number){setBusy(item.id);setError(null);const res=await fetch(`/api/materials/${item.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({delta})});setBusy(null);if(!res.ok){const b=await res.json().catch(()=>null);setError(b?.error??"Could not update stock.")}router.refresh()}
  async function photo(item:StockRow,file?:File){if(!file)return;try{setBusy(item.id);const commitToken=await upload(file);const r=await fetch("/api/item-photos/commit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({target:"material",targetId:item.id,commitToken})});const b=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.error||"Could not save photo");router.refresh()}catch(e){setError(e instanceof Error?e.message:"Could not save photo")}finally{setBusy(null)}}
  return <>
    <TopBar title="Materials" subtitle="Track stock levels" rightSlot={<button onClick={()=>setShowNew(true)} className="flex h-10 items-center gap-2 rounded-lg px-3.5 text-sm font-semibold" style={{background:UI.blue,color:"white"}}><Plus size={16}/> New stock item</button>}/>
    <div className="flex-1 overflow-auto p-3 md:p-4 xl:p-5" style={{background:"var(--app-bg, #03101f)"}}><div className="mx-auto w-full max-w-[1700px] space-y-3">
      <Metric label="Stock items" value={String(stocked.length)}/>
      {error&&<div className="rounded-xl px-4 py-3 text-sm" style={{color:UI.red,background:"rgba(255,94,114,.08)"}}>{error}</div>}
      <section className="overflow-hidden rounded-xl" style={{background:UI.panel,border:`1px solid ${UI.border}`}}>
        <div className="border-b p-3" style={{borderColor:UI.borderSoft}}><div className="relative max-w-md"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2" style={{color:UI.faint}}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search materials…" className="h-10 w-full rounded-lg pl-9 pr-3 text-sm" style={{background:"var(--brand-panel-deep, #041323)",color:UI.text,border:`1px solid ${UI.border}`}}/></div></div>
        {filtered.length===0?<div className="p-8 text-center text-sm" style={{color:UI.mute}}>No stock on hand.</div>:filtered.map(item=><div key={item.id} className="grid grid-cols-1 gap-3 border-b px-4 py-4 md:grid-cols-[80px_minmax(220px,1.4fr)_100px_110px_150px] md:items-center" style={{borderColor:UI.borderSoft}}>
          {item.hasPhoto?<button type="button" onClick={()=>setPhotoOpen(item)} className="h-20 w-20 overflow-hidden rounded-xl" aria-label={`Open ${item.name} photo`}><img src={`/api/item-photos/material/${item.id}`} alt={item.name} className="h-full w-full object-cover"/></button>:<div className="flex h-20 w-20 items-center justify-center rounded-xl" style={{background:UI.panelAlt,color:UI.faint}}><ImageIcon size={22}/></div>}
          <div className="min-w-0"><div className="flex items-center gap-2"><PackageSearch size={16} style={{color:UI.cyan}}/><div className="truncate text-sm font-semibold" style={{color:UI.text}}>{item.name}</div></div><div className="mt-1 text-[11px]" style={{color:UI.faint}}>{item.supplier??"No supplier"}</div><label className="mt-2 inline-flex cursor-pointer items-center gap-1.5 text-[11px] font-semibold" style={{color:UI.cyan}}><Camera size={13}/>{busy===item.id?"Uploading…":item.hasPhoto?"Change photo":"Add photo"}<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" className="hidden" disabled={busy===item.id} onChange={e=>void photo(item,e.target.files?.[0])}/></label></div>
          <span className="text-xs" style={{color:UI.mute}}>{item.unit}</span><span className="text-sm font-semibold" style={{color:UI.text}}>{item.onHand}</span>
          <div className="flex gap-2"><button disabled={busy===item.id||item.onHand===0} onClick={()=>void update(item,-1)} className="flex h-9 w-9 items-center justify-center rounded-lg disabled:opacity-40" style={{background:UI.panelAlt,color:UI.text}}><Minus size={15}/></button><button disabled={busy===item.id} onClick={()=>void update(item,1)} className="flex h-9 w-9 items-center justify-center rounded-lg disabled:opacity-40" style={{background:UI.panelAlt,color:UI.text}}><Plus size={15}/></button></div>
        </div>)}
      </section>
    </div></div>
    {photoOpen&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/90 p-4" onClick={()=>setPhotoOpen(null)}><button className="absolute right-4 top-4 rounded-full bg-black/60 p-3 text-white" onClick={()=>setPhotoOpen(null)} aria-label="Close photo"><X size={24}/></button><img src={`/api/item-photos/material/${photoOpen.id}`} alt={photoOpen.name} className="max-h-[88vh] max-w-[96vw] rounded-xl object-contain" onClick={e=>e.stopPropagation()}/><div className="absolute bottom-5 left-4 right-4 text-center text-sm font-semibold text-white">{photoOpen.name}</div></div>}
    {showNew&&<NewStockItem onClose={()=>setShowNew(false)} onDone={()=>{setShowNew(false);router.refresh()}}/>}
  </>
}

function NewStockItem({onClose,onDone}:{onClose:()=>void;onDone:()=>void}){const[name,setName]=useState(""),[unit,setUnit]=useState("each"),[onHand,setOnHand]=useState("0"),[supplier,setSupplier]=useState(""),[file,setFile]=useState<File|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null);const field={background:"var(--brand-panel-deep, #041323)",border:`1px solid ${UI.border}`,color:UI.text}as const;async function submit(e:React.FormEvent){e.preventDefault();try{setSaving(true);setError(null);const photoCommitToken=file?await upload(file):null;const res=await fetch("/api/materials",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,unit,onHand:Number(onHand),parLevel:0,supplier:supplier||null,photoCommitToken})});const b=await res.json().catch(()=>null);if(!res.ok)throw new Error(b?.error||"Could not create stock item");onDone()}catch(e){setError(e instanceof Error?e.message:"Could not create stock item")}finally{setSaving(false)}}return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/65 md:items-center md:p-4" onClick={onClose}><div className="w-full max-w-lg rounded-t-2xl p-5 md:rounded-2xl" style={{background:UI.panel,border:`1px solid ${UI.border}`}} onClick={e=>e.stopPropagation()}><div className="mb-4 flex justify-between"><h2 className="font-semibold" style={{color:UI.text}}>New stock item</h2><button onClick={onClose}><X size={18} style={{color:UI.mute}}/></button></div><form onSubmit={submit} className="flex flex-col gap-3"><Field title="Name"><input required value={name} onChange={e=>setName(e.target.value)} className="rounded-lg px-3 py-2.5" style={field}/></Field><div className="grid grid-cols-2 gap-3"><Field title="Unit"><input required value={unit} onChange={e=>setUnit(e.target.value)} className="rounded-lg px-3 py-2.5" style={field}/></Field><Field title="Supplier"><input value={supplier} onChange={e=>setSupplier(e.target.value)} className="rounded-lg px-3 py-2.5" style={field}/></Field></div><Field title="On hand"><input type="number" min="0" value={onHand} onChange={e=>setOnHand(e.target.value)} className="rounded-lg px-3 py-2.5" style={field}/></Field><label className="flex cursor-pointer items-center justify-center gap-2 rounded-lg py-3 text-sm font-semibold" style={{border:`1px solid ${UI.border}`,color:UI.cyan}}><Camera size={16}/>{file?file.name:"Take or choose photo"}<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" className="hidden" onChange={e=>setFile(e.target.files?.[0]??null)}/></label>{error&&<p className="text-xs" style={{color:UI.red}}>{error}</p>}<button disabled={saving} className="rounded-lg py-3 font-semibold" style={{background:UI.blue,color:"white"}}>{saving?"Saving…":"Create item"}</button></form></div></div>}
function Field({title,children}:{title:string;children:React.ReactNode}){return <label className="flex flex-col gap-1.5"><span className="text-xs" style={{color:UI.mute}}>{title}</span>{children}</label>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl p-4" style={{background:UI.panel,border:`1px solid ${UI.border}`}}><div className="text-[11px]" style={{color:UI.faint}}>{label}</div><div className="mt-1 text-xl font-semibold" style={{color:UI.text}}>{value}</div></div>}
