"use client";
import { useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Bell, Menu, X } from "lucide-react";
import type { Role } from "@prisma/client";
import type { YourPlanModule } from "@/lib/brand";
import { SCREEN_PATH } from "@/lib/access";
import { navGroupsFor } from "@/lib/nav";
import YourPlanLogo from "@/components/YourPlanLogo";
const UI={bg:"rgba(2,14,27,.97)",panel:"#07192b",border:"rgba(73,145,214,.22)",mute:"#93a8c1"};
type Brand={name:string;logoUrl:string|null;primaryColor:string;accentColor:string;modules:YourPlanModule[]}|null;
export default function MobileNav({role,brand}:{role:Role;brand?:Brand}){const pathname=usePathname();const groups=navGroupsFor(role,brand?.modules);const[open,setOpen]=useState(false);const primary=brand?.primaryColor||"#168dff";const accent=brand?.accentColor||"#25c7ff";const logo=brand?.logoUrl;const label=brand?.name||"Your Plan";return <><div className="fixed inset-x-0 top-0 z-50 flex h-14 items-center justify-between px-4 md:hidden" style={{background:UI.bg,borderBottom:`1px solid ${UI.border}`,backdropFilter:"blur(16px)"}}><button type="button" onClick={()=>setOpen(true)} aria-label="Open navigation" className="flex h-9 w-9 items-center justify-center rounded-lg" style={{background:UI.panel,border:`1px solid ${UI.border}`,color:UI.mute}}><Menu size={18}/></button><Link href="/" aria-label={`${label} home`} className="flex h-9 items-center justify-center">{logo?<img src={logo} alt={label} style={{maxWidth:112,maxHeight:38,objectFit:"contain",display:"block"}}/>:<YourPlanLogo width={112}/>}</Link><button type="button" aria-label="Notifications" className="relative flex h-9 w-9 items-center justify-center rounded-lg" style={{background:UI.panel,border:`1px solid ${UI.border}`,color:UI.mute}}><Bell size={16}/><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-rose-500"/></button></div>{open&&<div className="fixed inset-0 z-[60] md:hidden"><button type="button" aria-label="Close navigation overlay" className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={()=>setOpen(false)}/><aside className="absolute inset-y-0 left-0 w-[82%] max-w-[320px] overflow-y-auto p-4 shadow-2xl" style={{background:"linear-gradient(180deg,#02101f,#031321)",borderRight:`1px solid ${UI.border}`}}><div className="mb-6 flex items-center justify-between">{logo?<img src={logo} alt={label} style={{maxWidth:144,maxHeight:48,objectFit:"contain",display:"block"}}/>:<YourPlanLogo width={144}/>}<button type="button" onClick={()=>setOpen(false)} className="flex h-9 w-9 items-center justify-center rounded-lg" style={{background:UI.panel,border:`1px solid ${UI.border}`,color:UI.mute}}><X size={17}/></button></div><nav className="space-y-5">{groups.map((group,gi)=><div key={group.heading??gi}>{group.heading&&<p className="mb-2 px-2 text-[10px] font-semibold uppercase tracking-[0.13em]" style={{color:"#58718c"}}>{group.heading}</p>}<div className="space-y-1">{group.items.map(item=>{const href=SCREEN_PATH[item.screen];const active=pathname===href||pathname.startsWith(href+"/");const Icon=item.icon;return <Link key={item.screen} href={href} onClick={()=>setOpen(false)} className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium" style={{background:active?`linear-gradient(90deg,${primary}94,${primary}2e)`:"transparent",color:active?"#f4f8ff":UI.mute}}><Icon size={17} style={{color:active?accent:undefined}}/>{item.label}</Link>})}</div></div>)}</nav></aside></div>}</>}
