"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, CheckCircle2, KeyRound, ShieldCheck } from "lucide-react";
import YourPlanLogo from "@/components/YourPlanLogo";

const UI={panel:"#07192b",panelAlt:"#09213a",border:"rgba(77,150,221,.24)",borderSoft:"rgba(77,150,221,.12)",text:"#f5f9ff",mute:"#93a9c2",faint:"#617993",blue:"#168dff",cyan:"#25c7ff",green:"#18d3a0",red:"#ff5e72"};
export default function SetPasswordForm({token}:{token:string}){
 const router=useRouter();const[password,setPassword]=useState("");const[confirm,setConfirm]=useState("");const[error,setError]=useState<string|null>(null);const[loading,setLoading]=useState(false);const[done,setDone]=useState(false);
 async function onSubmit(e:React.FormEvent){e.preventDefault();setError(null);if(password.length<12)return setError("Use at least 12 characters.");if(password!==confirm)return setError("Passwords don't match.");setLoading(true);const res=await fetch("/api/set-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,password})});setLoading(false);if(!res.ok){const body=await res.json().catch(()=>null);setError(body?.error??"Could not set your password. The link may have expired.");return;}setDone(true);setTimeout(()=>router.push("/login"),1400);}
 const inputStyle:React.CSSProperties={background:"#041323",border:`1px solid ${UI.border}`,color:UI.text};
 return <section className="w-full max-w-lg rounded-2xl p-5 shadow-[0_28px_90px_rgba(0,0,0,.35)] sm:p-8" style={{background:UI.panel,border:`1px solid ${UI.border}`}}><div className="flex items-start gap-4"><YourPlanLogo width={170}/></div><div className="mt-7 flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl" style={{background:"rgba(22,141,255,.11)",color:UI.cyan,border:"1px solid rgba(37,199,255,.20)"}}><KeyRound size={18}/></span><div><p className="text-[10px] font-semibold uppercase tracking-[.16em]" style={{color:UI.cyan}}>Secure access</p><h1 className="mt-1 text-xl font-semibold" style={{color:UI.text}}>Set your password</h1><p className="mt-1 text-sm leading-6" style={{color:UI.mute}}>Choose a password for your YourPlan business portal account.</p></div></div>{done?<div className="mt-7 flex items-center gap-3 rounded-xl px-4 py-4 text-sm" style={{background:"rgba(25,211,162,.08)",border:"1px solid rgba(25,211,162,.22)",color:UI.green}}><CheckCircle2 size={18}/><div><p className="font-semibold">Password saved</p><p className="mt-0.5 text-xs opacity-80">Taking you to sign in…</p></div></div>:<form onSubmit={onSubmit} className="mt-7 flex flex-col gap-4"><label className="flex flex-col gap-1.5"><span className="text-xs font-medium" style={{color:UI.mute}}>New password</span><input type="password" autoComplete="new-password" required value={password} onChange={e=>setPassword(e.target.value)} className="h-11 rounded-lg px-3 text-sm outline-none" style={inputStyle} placeholder="At least 12 characters"/></label><label className="flex flex-col gap-1.5"><span className="text-xs font-medium" style={{color:UI.mute}}>Confirm password</span><input type="password" autoComplete="new-password" required value={confirm} onChange={e=>setConfirm(e.target.value)} className="h-11 rounded-lg px-3 text-sm outline-none" style={inputStyle} placeholder="••••••••••••"/></label><div className="flex gap-3 rounded-xl p-3" style={{background:UI.panelAlt,border:`1px solid ${UI.borderSoft}`}}><ShieldCheck size={15} className="mt-0.5 shrink-0" style={{color:UI.cyan}}/><p className="text-xs leading-5" style={{color:UI.faint}}>This secure link is single-use. After the password is saved, sign in with the email address your YourPlan administrator registered.</p></div>{error&&<div className="flex items-center gap-2 rounded-lg px-3 py-2.5 text-xs" style={{background:"rgba(255,94,114,.08)",border:"1px solid rgba(255,94,114,.22)",color:UI.red}}><AlertTriangle size={14}/>{error}</div>}<button type="submit" disabled={loading} className="mt-1 flex h-11 items-center justify-center gap-2 rounded-lg text-sm font-semibold disabled:opacity-60" style={{background:UI.blue,color:"white",boxShadow:"0 10px 28px rgba(22,141,255,.24)"}}><KeyRound size={16}/>{loading?"Saving…":"Set password"}</button></form>}</section>;
}
