"use client";

import { useEffect, useState } from "react";
import { Pencil, Save, Sparkles, X } from "lucide-react";

const UI={panel:"#07182b",border:"rgba(77,150,221,.24)",text:"#f6f9ff",mute:"#94a8c2",faint:"#627892",cyan:"#25c7ff",blue:"#1592ff"};

export default function WeeklyGoalCard(){
  const [goal,setGoal]=useState(""); const [draft,setDraft]=useState(""); const [editing,setEditing]=useState(false); const [saving,setSaving]=useState(false);
  useEffect(()=>{fetch("/api/weekly-goal").then(r=>r.ok?r.json():null).then(data=>{if(data){setGoal(data.goal||"");setDraft(data.goal||"");}}).catch(()=>{});},[]);
  async function save(){setSaving(true);const res=await fetch("/api/weekly-goal",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:draft})});const data=await res.json().catch(()=>null);if(res.ok){setGoal(data?.goal??draft.trim());setEditing(false);}setSaving(false);}
  return <section className="rounded-xl px-4 py-4 md:px-5" style={{background:"linear-gradient(135deg,rgba(21,146,255,.12),rgba(7,24,43,.98) 55%)",border:`1px solid ${UI.border}`,boxShadow:"0 18px 45px rgba(0,0,0,.16)"}}><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg" style={{background:"rgba(37,199,255,.11)",color:UI.cyan}}><Sparkles size={19}/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="text-[10px] font-semibold uppercase tracking-[.14em]" style={{color:UI.cyan}}>Goal of the week</p>{!editing&&<button type="button" onClick={()=>{setDraft(goal);setEditing(true);}} className="ml-auto flex items-center gap-1 rounded-md px-2 py-1 text-[11px] font-semibold" style={{color:UI.mute,border:`1px solid ${UI.border}`}}><Pencil size={12}/>{goal?"Edit":"Set goal"}</button>}</div>{editing?<div className="mt-2"><textarea autoFocus value={draft} maxLength={500} onChange={e=>setDraft(e.target.value)} placeholder="e.g. Finish every job clean, communicate clearly and leave every client impressed." rows={2} className="w-full resize-none rounded-lg px-3 py-2 text-sm outline-none" style={{background:"#041323",border:`1px solid ${UI.border}`,color:UI.text}}/><div className="mt-2 flex justify-end gap-2"><button type="button" onClick={()=>{setDraft(goal);setEditing(false);}} className="flex items-center gap-1 rounded-lg px-3 py-2 text-xs font-semibold" style={{color:UI.mute,border:`1px solid ${UI.border}`}}><X size={13}/>Cancel</button><button type="button" disabled={saving} onClick={()=>void save()} className="flex items-center gap-1 rounded-lg px-3 py-2 text-xs font-semibold disabled:opacity-60" style={{background:UI.blue,color:"white"}}><Save size={13}/>{saving?"Saving…":"Set for this week"}</button></div></div>:<p className="mt-1 text-base font-semibold leading-6 md:text-lg" style={{color:goal?UI.text:UI.faint}}>{goal||"Set a quote, focus or target for the team this week."}</p>}</div></div></section>;
}
