import Link from "next/link";
import { ArrowRight, BarChart3, BriefcaseBusiness, CalendarDays, CheckCircle2, ClipboardCheck, FileText, Layers3, Package, Sparkles, Users, WalletCards } from "lucide-react";

const nav = [["Features","/features"],["Industries","/industries"],["Pricing","/pricing"],["About","/about"],["Resources","/resources"],["Contact","/contact"]] as const;
const modules = [
  ["Jobs",BriefcaseBusiness],["Leads & CRM",Users],["Quotes",FileText],["Invoices",WalletCards],["Calendar",CalendarDays],["Staff",Users],["Timesheets",CheckCircle2],["Documents",FileText],["Stock",Package],["Inspections",ClipboardCheck],["Reporting",BarChart3],["AI & Automation",Sparkles]
] as const;

export function Wordmark(){return <Link href="/" aria-label="Your Plan" className="text-[26px] font-black tracking-[-.075em]"><span className="text-[#168dff]">your</span><span className="text-white"> plan</span></Link>}

export function PublicShell({children}:{children:React.ReactNode}){
  return <main className="min-h-screen bg-[#030b14] text-white">
    <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(110,126,145,.22),transparent_34%),radial-gradient(circle_at_80%_20%,rgba(22,141,255,.13),transparent_28%)]"/>
    <header className="relative z-20 border-b border-white/[.06] bg-[#07101a]/85 backdrop-blur-xl">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 md:px-8">
        <Wordmark/>
        <nav className="hidden items-center gap-6 lg:flex">{nav.map(([label,href])=><Link key={href} href={href} className="text-sm text-slate-300 hover:text-white">{label}</Link>)}</nav>
        <div className="flex items-center gap-2"><Link href="/login" className="rounded-full border border-white/12 px-4 py-2 text-sm font-semibold">Login</Link><Link href="/contact" className="hidden rounded-full bg-[#168dff] px-4 py-2 text-sm font-semibold sm:block">Book a Demo</Link></div>
      </div>
    </header>
    <div className="relative z-10">{children}</div>
    <footer className="relative z-10 border-t border-white/[.07] bg-[#020811]"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-10 md:grid-cols-[1.2fr_2fr] md:px-8"><div><Wordmark/><p className="mt-3 max-w-sm text-sm leading-6 text-slate-500">One platform. One subscription. Configured around the way your business actually works.</p></div><div className="grid grid-cols-2 gap-6 text-sm sm:grid-cols-3"><div><p className="font-semibold">Product</p><div className="mt-3 space-y-2 text-slate-500"><Link href="/features" className="block">Features</Link><Link href="/pricing" className="block">Pricing</Link><Link href="/industries" className="block">Industries</Link></div></div><div><p className="font-semibold">Company</p><div className="mt-3 space-y-2 text-slate-500"><Link href="/about" className="block">About</Link><Link href="/contact" className="block">Contact</Link><Link href="/login" className="block">Login</Link></div></div><div><p className="font-semibold">Resources</p><div className="mt-3 space-y-2 text-slate-500"><Link href="/resources" className="block">Guides</Link><span className="block">Help Centre</span><span className="block">Updates</span></div></div></div></div></footer>
  </main>
}

export function HomePage(){return <PublicShell>
  <section className="mx-auto max-w-7xl px-5 pb-10 pt-16 text-center md:px-8 md:pb-16 md:pt-24">
    <div className="mx-auto inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/[.05] px-4 py-2 text-[11px] font-semibold uppercase tracking-[.22em] text-cyan-200"><Layers3 size={14}/> One platform. Built around your business.</div>
    <h1 className="mx-auto mt-8 max-w-6xl text-5xl font-bold leading-[.98] tracking-[-.055em] sm:text-6xl md:text-7xl lg:text-[88px]"><span className="text-[#168dff]">Your</span> Business.<br/><span className="text-[#168dff]">Your</span> Way.<br/><span className="text-[#168dff]">Your</span> Plan.</h1>
    <p className="mx-auto mt-7 max-w-3xl text-base leading-7 text-slate-300 md:text-lg">All-in-one business management software for trade and service businesses. Manage jobs, customers, scheduling, quoting, invoicing, staff, stock, documents and automation from one place.</p>
    <div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link href="/contact" className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-[#168dff] px-6 font-semibold">Book a Demo <ArrowRight size={16}/></Link><Link href="/features" className="inline-flex h-12 items-center justify-center gap-2 rounded-xl border border-white/12 bg-white/[.03] px-6 font-semibold">See Features <ArrowRight size={16}/></Link></div>
    <DashboardPreview/>
  </section>
  <section className="border-y border-white/[.07] bg-[#0a4f91]"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-px px-4 py-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6">{modules.map(([name,Icon])=><div key={name} className="flex items-center justify-center gap-2 px-3 py-4 text-sm font-semibold"><Icon size={16}/>{name}</div>)}</div></section>
  <section className="mx-auto grid max-w-7xl gap-6 px-5 py-20 md:grid-cols-2 md:px-8 md:py-28"><div className="rounded-[28px] border border-white/[.08] bg-[#071522] p-8"><p className="text-xs font-semibold uppercase tracking-[.2em] text-cyan-300">Simple, transparent pricing</p><div className="mt-5 flex items-end gap-2"><span className="text-6xl font-bold">$50</span><span className="pb-2 text-slate-400">/ month</span></div><div className="mt-6 space-y-3 text-sm text-slate-300"><p>✓ $0 standard setup</p><p>✓ Cancel anytime</p><p>✓ Trial available on request</p><p>✓ Custom work quoted separately</p></div><Link href="/pricing" className="mt-7 inline-flex items-center gap-2 font-semibold text-cyan-300">View pricing <ArrowRight size={15}/></Link></div><div className="rounded-[28px] border border-white/[.08] bg-[#071522] p-8"><p className="text-xs font-semibold uppercase tracking-[.2em] text-cyan-300">Built for your industry</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.04em]">YourPlan adapts to your business, not the other way around.</h2><p className="mt-5 text-slate-400">Electrical, plumbing, landscaping, construction, mechanical and other service businesses can run from the same YourPlan foundation with their own branding, modules and workflows.</p><Link href="/industries" className="mt-7 inline-flex items-center gap-2 font-semibold text-cyan-300">Explore industries <ArrowRight size={15}/></Link></div></section>
</PublicShell>}

function DashboardPreview(){return <div className="relative mx-auto mt-16 max-w-6xl"><div className="pointer-events-none absolute -inset-10 rounded-[50px] bg-[radial-gradient(circle_at_50%_35%,rgba(22,141,255,.34),rgba(37,199,255,.06)_38%,transparent_68%)] blur-3xl"/><div className="relative overflow-hidden rounded-[28px] border border-white/15 bg-[#061321] p-5 text-left shadow-[0_35px_120px_rgba(0,0,0,.55)] md:p-7"><div className="flex items-center justify-between border-b border-white/[.07] pb-4"><div><p className="font-semibold">Business overview</p><p className="mt-1 text-xs text-slate-500">Everything moving in one workspace</p></div><span className="rounded-full border border-emerald-300/20 bg-emerald-300/[.06] px-3 py-1 text-[10px] font-semibold uppercase tracking-wider text-emerald-300">Live operations</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Open jobs","18"],["Leads","7"],["Quotes","12"],["Team today","9"]].map(([l,v])=><div key={l} className="rounded-xl border border-white/[.07] bg-[#04111e] p-4"><p className="text-[10px] uppercase tracking-wider text-slate-600">{l}</p><p className="mt-2 text-2xl font-semibold">{v}</p></div>)}</div><div className="mt-3 grid gap-3 lg:grid-cols-[1.25fr_.75fr]"><div className="rounded-2xl border border-white/[.07] bg-[#04111e] p-4"><p className="text-xs font-semibold text-slate-300">Today&apos;s schedule</p><div className="mt-4 space-y-3">{["8:00 · Site visit","10:30 · Project install","1:00 · Client meeting"].map(x=><div key={x} className="rounded-xl border border-white/[.06] bg-white/[.02] px-3 py-3 text-xs text-slate-300">{x}</div>)}</div></div><div className="rounded-2xl border border-white/[.07] bg-[#04111e] p-4"><p className="text-xs font-semibold text-slate-300">Business modules</p><div className="mt-4 flex flex-wrap gap-2">{["Jobs","CRM","Quotes","Invoices","Team","Timesheets","Stock","Reports"].map(x=><span key={x} className="rounded-lg border border-cyan-300/10 bg-cyan-300/[.04] px-2.5 py-1.5 text-[10px] text-slate-400">{x}</span>)}</div></div></div></div></div>}

const pageCopy = {
features:{eyebrow:"Everything in one place",title:"Run the whole business from one platform.",body:"YourPlan brings the day-to-day operation together without forcing every company into the same workflow."},
pricing:{eyebrow:"Simple pricing",title:"$50 per month. $0 standard setup.",body:"One straightforward subscription with cancel-anytime flexibility. Trials are available on request and custom functionality can be scoped separately."},
about:{eyebrow:"Why YourPlan",title:"Business software built around the business.",body:"YourPlan exists to replace disconnected admin tools with one configurable operating system for everyday businesses."},
industries:{eyebrow:"Built to adapt",title:"One foundation. Different industries. Your workflow.",body:"Configure branding, permissions, modules and workflows for electrical, landscaping, mechanical, construction and other service businesses."},
resources:{eyebrow:"Resources",title:"Practical help for teams using YourPlan.",body:"Guides, onboarding material, workflow help and product updates will live here as the platform grows."},
contact:{eyebrow:"Book a demo",title:"Show us how your business works.",body:"We’ll configure YourPlan around the way your team actually operates, then show you the workflow end to end."}
} as const;

export function InfoPage({kind}:{kind:keyof typeof pageCopy}){const c=pageCopy[kind];return <PublicShell><section className="mx-auto max-w-7xl px-5 py-20 md:px-8 md:py-28"><p className="text-xs font-semibold uppercase tracking-[.22em] text-cyan-300">{c.eyebrow}</p><h1 className="mt-5 max-w-4xl text-5xl font-bold tracking-[-.05em] md:text-7xl">{c.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-400">{c.body}</p>{kind==="features"&&<div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{modules.map(([name,Icon])=><div key={name} className="rounded-2xl border border-white/[.08] bg-[#071522] p-6"><Icon className="text-cyan-300" size={20}/><h2 className="mt-5 font-semibold">{name}</h2><p className="mt-2 text-sm leading-6 text-slate-500">Configured into the same connected YourPlan workspace.</p></div>)}</div>}{kind==="pricing"&&<div className="mt-12 max-w-xl rounded-[28px] border border-cyan-300/15 bg-[#071522] p-8"><div className="flex items-end gap-2"><span className="text-6xl font-bold">$50</span><span className="pb-2 text-slate-400">/ month</span></div><div className="mt-6 space-y-3 text-slate-300"><p>✓ $0 standard setup</p><p>✓ Cancel anytime</p><p>✓ Trial on request</p><p>✓ Custom work quoted separately</p></div></div>}{kind==="contact"&&<div className="mt-10"><Link href="mailto:hello@your-plan.com.au" className="inline-flex items-center gap-2 rounded-xl bg-[#168dff] px-6 py-3 font-semibold">Contact YourPlan <ArrowRight size={16}/></Link></div>}</section></PublicShell>}
