import Link from "next/link";
import { notFound } from "next/navigation";
import { Bell, Building2, FileText, Layers3, LockKeyhole, ShieldCheck, UsersRound, Wrench } from "lucide-react";
import { requireUser } from "@/lib/session";
import { prisma } from "@/lib/prisma";
import TopBar from "@/components/TopBar";
const UI={panel:"var(--brand-panel, #07192b)",panelAlt:"var(--brand-panel-alt, #09213a)",border:"var(--brand-border, rgba(77,150,221,.24))",borderSoft:"var(--brand-border-soft, rgba(77,150,221,.12))",text:"#f5f9ff",mute:"var(--brand-muted, #93a9c2)",faint:"var(--brand-faint, #617993)",cyan:"var(--brand-accent, #25c7ff)",green:"#18d3a0",orange:"#ff9f1c"};
export default async function SettingsPage(){
  const user=await requireUser();
  if(user.role!=="ADMIN")notFound();
  const isPlatformAdmin=!user.businessId;
  const portalName=user.business?.name??"YourPlan";
  const team=await prisma.user.findMany({where:isPlatformAdmin?{}:{businessId:user.businessId!},select:{id:true,name:true,role:true,active:true},orderBy:{name:"asc"}});
  const businesses=isPlatformAdmin?await prisma.businessPortal.count():1;
  const checks=[{label:"Database configured",ready:Boolean(process.env.DATABASE_URL),detail:"Required for portal and customer data."},{label:"Authentication secret",ready:Boolean(process.env.AUTH_SECRET&&process.env.AUTH_SECRET!=="replace-me"),detail:"Production authentication is protected with a unique secret."},{label:"Trusted production host",ready:process.env.AUTH_TRUST_HOST==="true",detail:"Allows secure authentication behind the production domain."},{label:"Portal URL configured",ready:Boolean(process.env.NEXTAUTH_URL?.startsWith("https://")),detail:"Production authentication uses the secure portal domain."}];
  const cards=[
    ...(isPlatformAdmin?[{href:"/platform",icon:Layers3,title:"Your Plan Platform",detail:`Create and manage customer businesses · ${businesses} configured`}]:[]),
    {href:"/account",icon:UsersRound,title:"Profile",detail:"Manage your personal account and password"},
    ...(!isPlatformAdmin?[{href:"/employees",icon:ShieldCheck,title:"Users & permissions",detail:"Manage team access and roles"},{href:"/settings/audit",icon:FileText,title:"Audit log",detail:"Review sensitive portal activity"},{href:"/documents",icon:Building2,title:"Company documents",detail:"Open managed business documents"},{href:"/calendar",icon:Wrench,title:"Jobs & scheduling",detail:"Manage operational scheduling"},{href:"/reminders",icon:Bell,title:"Notifications",detail:"Review reminders and follow-ups"}]:[])
  ];
  return <><TopBar title="Settings" subtitle={`Manage ${portalName}, security and portal configuration`}/><div className="flex-1 overflow-auto p-4 md:p-5" style={{background:"var(--app-bg, #03101f)"}}><div className="mx-auto max-w-[1500px] space-y-4"><section className="grid gap-3 sm:grid-cols-3"><Metric label="Active users" value={String(team.filter(x=>x.active).length)}/><Metric label={isPlatformAdmin?"Customer businesses":"Business portal"} value={isPlatformAdmin?String(businesses):"1"}/><Metric label="Portal" value={portalName}/></section><section className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{cards.map(({href,icon:Icon,title,detail})=><Link key={href} href={href} className="rounded-xl p-4 transition hover:-translate-y-0.5" style={{background:UI.panel,border:`1px solid ${UI.border}`}}><div className="flex gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl" style={{background:"rgb(var(--brand-primary-rgb, 22 141 255) / .11)",color:UI.cyan}}><Icon size={18}/></span><div><h2 className="text-sm font-semibold" style={{color:UI.text}}>{title}</h2><p className="mt-1 text-xs leading-5" style={{color:UI.mute}}>{detail}</p></div></div></Link>)}</section><section className="overflow-hidden rounded-xl" style={{background:UI.panel,border:`1px solid ${UI.border}`}}><div className="flex items-center justify-between border-b px-5 py-4" style={{borderColor:UI.borderSoft}}><div><h2 className="text-sm font-semibold" style={{color:UI.text}}>Production readiness</h2><p className="mt-1 text-xs" style={{color:UI.faint}}>Security configuration status. Secret values are never displayed.</p></div><LockKeyhole size={18} style={{color:UI.cyan}}/></div>{checks.map(c=><div key={c.label} className="flex items-start justify-between gap-4 border-b px-5 py-4" style={{borderColor:UI.borderSoft}}><div><p className="text-sm font-semibold" style={{color:UI.text}}>{c.label}</p><p className="mt-1 text-xs" style={{color:UI.faint}}>{c.detail}</p></div><span className="rounded-full px-2.5 py-1 text-[10px] font-semibold" style={{background:c.ready?"rgba(25,211,162,.10)":"rgba(255,159,28,.10)",color:c.ready?UI.green:UI.orange}}>{c.ready?"Ready":"Needs setup"}</span></div>)}</section></div></div></>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl p-4" style={{background:UI.panel,border:`1px solid ${UI.border}`}}><p className="text-[11px]" style={{color:UI.faint}}>{label}</p><p className="mt-1 text-xl font-semibold" style={{color:UI.text}}>{value}</p></div>}
