import { NextResponse } from "next/server";
import { z } from "zod";
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { getSessionUser } from "@/lib/session";
import { EVENT_TYPES } from "@/lib/theme";
import { recordAudit } from "@/lib/audit";

const eventSchema=z.object({title:z.string().trim().max(120).optional().nullable(),notes:z.string().trim().max(2000).optional().nullable(),type:z.enum(EVENT_TYPES),jobId:z.string().cuid().optional().nullable(),assignedToId:z.string().cuid().optional().nullable(),assignedToIds:z.array(z.string().cuid()).max(50).optional(),startsAt:z.string().datetime(),endsAt:z.string().datetime()}).refine(d=>new Date(d.endsAt)>new Date(d.startsAt),{message:"End time must be after start time",path:["endsAt"]});
async function context(){const user=await getSessionUser();if(!user||!user.businessId)return null;return{user,businessId:user.businessId}}
export async function GET(){const ctx=await context();if(!ctx)return NextResponse.json({error:"Unauthorized or no active customer business selected"},{status:401});const{user,businessId}=ctx;const tenantScope={OR:[{job:{businessId}},{jobId:null,assignedTo:{businessId}}]};const events=await prisma.jobEvent.findMany({where:tenantScope,select:{id:true,title:true,notes:true,type:true,startsAt:true,endsAt:true,assignedTo:{select:{id:true,name:true,email:true}},job:{select:{id:true,title:true,address:true,status:true,client:{select:{id:true,name:true}}}}},orderBy:{startsAt:"asc"}});const ids=events.map(e=>e.id);const assignments=ids.length?await prisma.$queryRaw<Array<{eventId:string;userId:string;name:string}>>(Prisma.sql`SELECT a."eventId",a."userId",u."name" FROM "JobEventAssignee" a JOIN "User" u ON u."id"=a."userId" WHERE a."eventId" IN (${Prisma.join(ids)})`):[];const byEvent=new Map<string,Array<{id:string;name:string}>>();for(const a of assignments)byEvent.set(a.eventId,[...(byEvent.get(a.eventId)||[]),{id:a.userId,name:a.name}]);const out=events.map(e=>({...e,assignedToIds:(byEvent.get(e.id)||[]).map(a=>a.id),assignedToNames:(byEvent.get(e.id)||[]).map(a=>a.name)}));return NextResponse.json(user.role==="EMPLOYEE"?out.filter(e=>e.assignedToIds.includes(user.id)||e.assignedTo?.id===user.id):out)}
export async function POST(req:Request){const ctx=await context();if(!ctx)return NextResponse.json({error:"Unauthorized"},{status:401});const{user,businessId}=ctx;const parsed=eventSchema.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:"Invalid input",issues:parsed.error.flatten()},{status:400});const d=parsed.data;if(user.role==="EMPLOYEE"&&(d.type==="job"||d.jobId))return NextResponse.json({error:"Job scheduling must be done by an admin or supervisor"},{status:403});let ids=user.role==="EMPLOYEE"?[user.id]:[...new Set(d.assignedToIds??(d.assignedToId?[d.assignedToId]:[]))];if(!ids.length&&!d.jobId)ids=[user.id];if(ids.length){const valid=await prisma.user.findMany({where:{id:{in:ids},businessId,active:true},select:{id:true}});if(valid.length!==ids.length)return NextResponse.json({error:"One or more assignees are invalid or inactive"},{status:400})}if(d.jobId){const job=await prisma.job.findFirst({where:{id:d.jobId,businessId},select:{id:true}});if(!job)return NextResponse.json({error:"Job not found for this business"},{status:404})}const primary=ids[0]??null,startsAt=new Date(d.startsAt),endsAt=new Date(d.endsAt);try{const event=await prisma.$transaction(async tx=>{const created=await tx.jobEvent.create({data:{title:d.title?.trim()||null,notes:d.notes?.trim()||null,type:d.type,jobId:d.jobId??null,assignedToId:primary,startsAt,endsAt}});for(const id of ids)await tx.$executeRaw`INSERT INTO "JobEventAssignee" ("eventId","userId") VALUES (${created.id},${id}) ON CONFLICT DO NOTHING`;if(d.type==="job"&&d.jobId){const existing=await tx.job.findFirst({where:{id:d.jobId,businessId},select:{status:true}});if(!existing)throw new Error("JOB_NOT_FOUND");await tx.job.updateMany({where:{id:d.jobId,businessId},data:{scheduledStart:startsAt,scheduledEnd:endsAt,assignedToId:primary,...(existing.status==="QUOTED"?{status:"SCHEDULED" as const}:{})}})}return created});if(d.type==="job"&&d.jobId)await recordAudit({actor:user,action:"CALENDAR_JOB_EVENT_CREATED",entityType:"JobEvent",entityId:event.id,details:{businessId,jobId:d.jobId,assignedToIds:ids}});return NextResponse.json({...event,assignedToIds:ids},{status:201})}catch{return NextResponse.json({error:"Could not create event (check job/assignee)"},{status:400})}}
