import Link from "next/link";
import { notFound } from "next/navigation";
import { CalendarDays, ChevronLeft, MapPin } from "lucide-react";
import { getPlatformAdmin } from "@/lib/platform-admin";
const green="#69be28",dark="#080a0b",panel="#111416",border="#2a3033",muted="#9aa3a7";
const events=[
 {round:"AUSX 01",place:"Townsville",date:"3 Oct",type:"Supercross",status:"Upcoming"},
 {round:"AUSX 02",place:"Auckland",date:"31 Oct",type:"Supercross",status:"Upcoming"},
 {round:"AUSX 03",place:"Geelong",date:"7 Nov",type:"Supercross",status:"Upcoming"},
 {round:"AUSX 04",place:"Perth",date:"14 Nov",type:"Supercross",status:"Upcoming"},
 {round:"AUSX 05",place:"Newcastle",date:"28 Nov",type:"Supercross",status:"Upcoming"},
 {round:"MX Series",place:"Motocross championship",date:"Season",type:"Motocross",status:"Optional series"}
];
export default async function Calendar(){const user=await getPlatformAdmin();if(!user)notFound();return <main className="min-h-screen text-white" style={{background:dark}}><header className="border-b" style={{borderColor:border}}><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3 md:px-6"><Link href="/hq/demos/empire" className="flex items-center gap-1 text-xs" style={{color:muted}}><ChevronLeft size={15}/>Empire HQ</Link><span className="text-[10px] font-bold uppercase tracking-[.25em]" style={{color:green}}>Race Calendar · Demo</span></div></header><div className="mx-auto max-w-6xl p-4 md:p-6"><section className="rounded-2xl border p-6 md:p-8" style={{background:"linear-gradient(125deg,#111416,#0b0d0e 70%,#15220e)",borderColor:border}}><div className="flex items-center gap-3"><CalendarDays style={{color:green}}/><div><p className="text-xs font-bold uppercase tracking-[.25em]" style={{color:green}}>2026 race program</p><h1 className="mt-1 text-3xl font-black uppercase md:text-4xl">Empire Race Calendar</h1></div></div><p className="mt-4 max-w-2xl text-sm leading-6" style={{color:muted}}>Supercross is the current priority. Other championships can be added as separate series without changing the Empire workflow.</p></section><section className="mt-5 grid gap-3">{events.map((e,i)=><div key={e.round} className="grid gap-3 rounded-xl border p-5 md:grid-cols-[110px_1fr_150px_130px] md:items-center" style={{background:panel,borderColor:i===0?"rgba(105,190,40,.55)":border}}><div><p className="text-[10px] font-bold uppercase tracking-widest" style={{color:green}}>{e.round}</p><p className="mt-1 text-xl font-black">{e.date}</p></div><div><p className="flex items-center gap-2 font-bold"><MapPin size={15} style={{color:green}}/>{e.place}</p><p className="mt-1 text-xs" style={{color:muted}}>{e.type} · Team schedule, notes, setup, timings and chat linked to event</p></div><span className="text-xs" style={{color:muted}}>{e.type}</span><span className="w-fit rounded-full border px-3 py-1 text-[10px] font-bold uppercase tracking-widest" style={{borderColor:i===0?green:border,color:i===0?green:muted}}>{e.status}</span></div>)}</section></div></main>}
