import Link from "next/link";
import { notFound } from "next/navigation";
import { CalendarDays, ChevronLeft, ClipboardList, Clock3, FileText, Flag, Gauge, Radio, Users, Wrench } from "lucide-react";
import { getPlatformAdmin } from "@/lib/platform-admin";

const green="#69be28", dark="#080a0b", panel="#111416", border="#2a3033", muted="#9aa3a7";
const riders=[{name:"Brad West",number:"100"},{name:"Dean Ferris",number:"111"},{name:"Ryan Alexanderson",number:"63"}];
const modules=[
 {title:"Race Calendar",text:"Race weekends, testing, travel and team commitments.",icon:CalendarDays},
 {title:"Race Notes",text:"Track conditions, setup notes and rider feedback by session.",icon:ClipboardList},
 {title:"Race Timings",text:"Practice, qualifying and race timing with rider/session dropdowns.",icon:Clock3},
 {title:"Riders",text:"Profiles, bike allocation, notes and rider-specific records.",icon:Flag},
 {title:"Team",text:"Crew directory, roles, access and internal information.",icon:Users},
 {title:"Bike Setup",text:"Setup sheets and changes recorded against rider and event.",icon:Wrench},
 {title:"Equipment",text:"Team equipment, service status and assigned assets.",icon:Gauge},
 {title:"Documents",text:"Team documents, event files and shared resources.",icon:FileText},
 {title:"Team Comms",text:"Private team and job/event chats with media access.",icon:Radio},
];
export default async function EmpireDemo(){const user=await getPlatformAdmin();if(!user)notFound();return <main className="min-h-screen text-white" style={{background:dark}}>
 <header className="sticky top-0 z-20 border-b" style={{background:"rgba(8,10,11,.96)",borderColor:border}}><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-3 md:px-6"><div className="flex items-center gap-4"><Link href="/hq/demos" className="flex items-center gap-1 text-xs" style={{color:muted}}><ChevronLeft size={15}/>Client Demos</Link><div className="hidden h-7 w-px md:block" style={{background:border}}/><div><p className="text-[10px] font-bold uppercase tracking-[.28em]" style={{color:green}}>Penrite Racing</p><h1 className="text-lg font-black uppercase tracking-tight">Empire Kawasaki</h1></div></div><span className="rounded-full border px-3 py-1 text-[10px] font-bold uppercase tracking-widest" style={{borderColor:green,color:green}}>Demo mode</span></div></header>
 <div className="mx-auto max-w-7xl p-4 md:p-6"><section className="relative overflow-hidden rounded-2xl border p-6 md:p-10" style={{background:"linear-gradient(125deg,#111416 0%,#0b0d0e 62%,#15220e 100%)",borderColor:border}}><div className="absolute right-[-80px] top-[-120px] h-80 w-80 rounded-full opacity-20" style={{background:green,filter:"blur(80px)"}}/><div className="relative max-w-3xl"><p className="text-xs font-black uppercase tracking-[.3em]" style={{color:green}}>Empire HQ · Powered by YourPlan</p><h2 className="mt-3 text-3xl font-black uppercase leading-none md:text-5xl">Race team operations.<br/><span style={{color:green}}>One team portal.</span></h2><p className="mt-5 max-w-2xl text-sm leading-6" style={{color:muted}}>Private demonstration environment for Penrite Racing Empire Kawasaki. Explore the proposed race-team workflow without affecting a live client portal.</p></div></section>
 <section className="mt-5 grid gap-3 md:grid-cols-3">{riders.map(r=><div key={r.number} className="flex items-center justify-between rounded-xl border p-5" style={{background:panel,borderColor:border}}><div><p className="text-xs uppercase tracking-widest" style={{color:muted}}>Rider</p><p className="mt-1 font-bold">{r.name}</p></div><div className="text-4xl font-black italic" style={{color:green}}>#{r.number}</div></div>)}</section>
 <section className="mt-7"><div className="mb-3 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-widest" style={{color:green}}>Portal walkthrough</p><h3 className="mt-1 text-xl font-bold">Empire HQ modules</h3></div><span className="hidden text-xs md:block" style={{color:muted}}>Client presentation environment</span></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{modules.map(({title,text,icon:Icon})=><div key={title} className="group rounded-xl border p-5 transition hover:-translate-y-0.5" style={{background:panel,borderColor:border}}><div className="flex h-9 w-9 items-center justify-center rounded-lg" style={{background:"rgba(105,190,40,.12)",color:green}}><Icon size={18}/></div><h4 className="mt-4 font-bold">{title}</h4><p className="mt-2 text-xs leading-5" style={{color:muted}}>{text}</p><div className="mt-4 text-[10px] font-bold uppercase tracking-widest" style={{color:green}}>Demo screen →</div></div>)}</div></section>
 <section className="mt-7 grid gap-3 lg:grid-cols-2"><div className="rounded-xl border p-5" style={{background:panel,borderColor:border}}><p className="text-xs font-bold uppercase tracking-widest" style={{color:green}}>Upcoming</p><h3 className="mt-2 font-bold">Race weekend overview</h3><div className="mt-4 space-y-3">{["Team arrival & setup","Practice / qualifying","Race program"].map((x,i)=><div key={x} className="flex items-center justify-between border-b pb-3 text-sm" style={{borderColor:border}}><span>{x}</span><span className="text-xs" style={{color:muted}}>Demo day {i+1}</span></div>)}</div></div><div className="rounded-xl border p-5" style={{background:panel,borderColor:border}}><p className="text-xs font-bold uppercase tracking-widest" style={{color:green}}>Presentation note</p><h3 className="mt-2 font-bold">Built to become the live portal</h3><p className="mt-3 text-sm leading-6" style={{color:muted}}>The demo is deliberately structured like the finished Empire portal. Once the agreed workflow and branding are approved, the configuration can become the starting point for onboarding rather than rebuilding the concept from scratch.</p></div></section>
 </div></main>}
