import { PrismaClient } from "@prisma/client";
import { createWorker } from "tesseract.js";
import { createDownloadUrl } from "../src/lib/storage";
const prisma=new PrismaClient();
const brands=["Voltex","Clipsal","Hager","NHP","Legrand","Trader","HPM","Deta","Cabac","Schneider","NB Lights","SAL","Pierlite","Brilliant"];
function parse(text:string,barcode=""){const lines=text.split(/\n/).map(x=>x.replace(/[|_]+/g," ").replace(/\s+/g," ").trim()).filter(x=>x.length>2);const supplier=brands.find(b=>text.toLowerCase().includes(b.toLowerCase()))||null;const compact=(x:string)=>x.replace(/\s+/g,"");const modelLike=(x:string)=>x===barcode||/^[A-Z]{1,6}[A-Z0-9-]{2,12}$/i.test(compact(x))||/^\d{5,14}$/.test(compact(x));const junk=(x:string)=>/barcode|batch|voltage|watt|colour|color|serial|www\.|\.com/i.test(x);const productWords=/(mounting\s*block|socket|outlet|switch|plug|light|lamp|downlight|batten|gpo|power\s*point|junction\s*box|enclosure|fan|dimmer|sensor|breaker|rcbo|rccb|isolator|transformer|driver|cable|conduit|coupler|adapter|connector|plate|mechanism|smoke\s*alarm|pendant|floodlight)/i;let desc=lines.find(x=>productWords.test(x)&&!modelLike(x)&&!junk(x))||lines.find(x=>/[A-Za-z]{4,}/.test(x)&&x.split(/\s+/).length>=2&&!modelLike(x)&&!junk(x)&&!brands.some(b=>x.toLowerCase()===b.toLowerCase()))||"";if(desc&&supplier&&!desc.toLowerCase().includes(supplier.toLowerCase()))desc=`${supplier} ${desc}`;desc=desc.replace(/\b[A-Z]{1,6}\d[A-Z0-9-]{1,10}\b/gi,"").replace(/\s+/g," ").trim();return{name:desc.slice(0,160),supplier}}
function machineLike(name:string,barcode:string|null){const n=name.replace(/\s+/g,"");return name===barcode||/^[A-Z]{1,6}[A-Z0-9-]{2,12}$/i.test(n)||/^\d{5,14}$/.test(n)}
async function main(){await prisma.scanEnrichmentJob.updateMany({where:{status:"PROCESSING",updatedAt:{lt:new Date(Date.now()-15*60*1000)}},data:{status:"PENDING",lastError:"Recovered stale processing job"}});const jobs=await prisma.scanEnrichmentJob.findMany({where:{status:"PENDING"},orderBy:{createdAt:"asc"},take:25,include:{stockItem:true}});if(!jobs.length){console.log("No pending scan enrichment jobs");return}const worker=await createWorker("eng");try{for(const job of jobs){await prisma.scanEnrichmentJob.update({where:{id:job.id},data:{status:"PROCESSING",attempts:{increment:1},lastError:null}});try{const url=createDownloadUrl(job.photoStorageKey);const image=await fetch(url);if(!image.ok)throw new Error(`photo download ${image.status}`);const bytes=Buffer.from(await image.arrayBuffer());const out=await worker.recognize(bytes);const p=parse(out.data.text||"",job.stockItem.barcode||"");if(!p.name)throw new Error("No human-readable product description found");if(machineLike(job.stockItem.name,job.stockItem.barcode)){await prisma.stockItem.update({where:{id:job.stockItemId},data:{name:p.name,supplier:p.supplier||job.stockItem.supplier}})}await prisma.scanEnrichmentJob.update({where:{id:job.id},data:{status:"DONE",lastError:null}});console.log(`Done ${job.stockItem.barcode||job.stockItemId}: ${p.name}`)}catch(e){const msg=e instanceof Error?e.message:String(e);const attempts=job.attempts+1;await prisma.scanEnrichmentJob.update({where:{id:job.id},data:{status:attempts>=3?"FAILED":"PENDING",lastError:msg.slice(0,500)}});console.error(`Failed ${job.id}: ${msg}`)}}}finally{await worker.terminate()}}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>prisma.$disconnect());
