import Link from "next/link";
import { notFound } from "next/navigation";
import { ChevronLeft } from "lucide-react";
import { getPlatformAdmin } from "@/lib/platform-admin";

const green="#69be28", dark="#080a0b", panel="#111416", border="#2a3033", muted="#9aa3a7";
const riders=[{name:"Brad West",number:"100"},{name:"Dean Ferris",number:"111"},{name:"Ryan Alexanderson",number:"63"}];
const sections={
 calendar:{title:"Race Calendar",subtitle:"Race weekends, testing and team commitments",rows:["Round 1 · Team arrival & setup","Practice / Qualifying","Race Day","Testing Day · Bike development"]},
 notes:{title:"Race Notes",subtitle:"Track, setup and rider feedback",rows:["Track conditions · Dry / hard pack","Brad West #100 · Front-end confidence notes","Dean Ferris #111 · Corner entry setup","Ryan Alexanderson #63 · Suspension feedback"]},
 timings:{title:"Race Timings",subtitle:"Session timing by rider and event",rows:["Practice · #100 · 1:42.318","Qualifying · #111 · 1:40.884","Moto 1 · #63 · 1:41.205","Moto 2 · Team comparison"]},
 riders:{title:"Riders",subtitle:"Rider profiles and team records",rows:riders.map(r=>`${r.name} · #${r.number}`)},
 team:{title:"Team",subtitle:"Crew directory, roles and access",rows:["Team Manager · Full access","Mechanics · Rider / bike access","Race Crew · Event access","Media / Admin · Communications & documents"]},
 setup:{title:"Bike Setup",subtitle:"Setup sheets and changes by rider",rows:["#100 · Suspension baseline","#111 · Gearing / chassis notes","#63 · Start setup","Event comparison · Previous round"]},
 equipment:{title:"Equipment",subtitle:"Race-team assets and service status",rows:["Race bikes · Assigned by rider","Generators · Service current","Pit equipment · Loaded","Timing / communications gear · Ready"]},
 documents:{title:"Documents",subtitle:"Shared team and event files",rows:["Race weekend run sheet","Track maps & event information","Team procedures","Sponsor / media documents"]},
 comms:{title:"Team Comms",subtitle:"Private conversations and event channels",rows:["Round 1 · Whole team","#100 Crew · Brad West","#111 Crew · Dean Ferris","#63 Crew · Ryan Alexanderson"]}
} as const;

type Key=keyof typeof sections;
export default async function EmpireSection({params}:{params:Promise<{section:string}>}){const user=await getPlatformAdmin();if(!user)notFound();const {section}=await params;const data=sections[section as Key];if(!data)notFound();return <main className="min-h-screen text-white" style={{background:dark}}><header className="sticky top-0 z-20 border-b" style={{background:"rgba(8,10,11,.96)",borderColor:border}}><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3 md:px-6"><Link href="/hq/demos/empire" className="flex items-center gap-1 text-xs" style={{color:muted}}><ChevronLeft size={15}/>Empire HQ</Link><div className="text-right"><p className="text-[10px] font-bold uppercase tracking-[.25em]" style={{color:green}}>Penrite Racing Empire Kawasaki</p><p className="text-xs" style={{color:muted}}>Demo mode</p></div></div></header><div className="mx-auto max-w-6xl p-4 md:p-6"><section className="rounded-2xl border p-6 md:p-8" style={{background:"linear-gradient(125deg,#111416,#0b0d0e 70%,#15220e)",borderColor:border}}><p className="text-xs font-black uppercase tracking-[.28em]" style={{color:green}}>Empire HQ</p><h1 className="mt-2 text-3xl font-black uppercase md:text-4xl">{data.title}</h1><p className="mt-2 text-sm" style={{color:muted}}>{data.subtitle}</p></section><section className="mt-5 grid gap-3">{data.rows.map((row,i)=><div key={row} className="flex items-center justify-between rounded-xl border p-5" style={{background:panel,borderColor:border}}><div><p className="text-[10px] font-bold uppercase tracking-widest" style={{color:green}}>Demo record {String(i+1).padStart(2,"0")}</p><p className="mt-2 font-semibold">{row}</p></div><span className="rounded-full border px-3 py-1 text-[10px] font-bold uppercase tracking-widest" style={{borderColor:"rgba(105,190,40,.4)",color:green}}>Open</span></div>)}</section><section className="mt-5 rounded-xl border p-5" style={{background:panel,borderColor:border}}><p className="text-sm leading-6" style={{color:muted}}>This is presentation-safe demo data only. The live Empire portal can use the same workflow with real team records, permissions and event information once approved.</p></section></div></main>}
