"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Barcode, Camera, Check, Loader2, PackagePlus, Plus } from "lucide-react";

type Result={id:string;name:string;onHand:number;unit:string;barcode?:string|null};
type UnknownState={barcode:string;name?:string;supplier?:string;busy?:boolean};

declare global { interface Window { Quagga?: any; Tesseract?: any; webkitAudioContext?: typeof AudioContext } }

const QUAGGA_SRC="https://cdn.jsdelivr.net/npm/@ericblade/quagga2@1.8.4/dist/quagga.min.js";
const TESSERACT_SRC="https://cdn.jsdelivr.net/npm/tesseract.js@6.0.1/dist/tesseract.min.js";

function loadScript(src:string,id:string){return new Promise<void>((resolve,reject)=>{if(document.getElementById(id))return resolve();const s=document.createElement("script");s.id=id;s.src=src;s.async=true;s.onload=()=>resolve();s.onerror=()=>reject(new Error(`Could not load ${id}`));document.head.appendChild(s)})}
function cleanLine(v:string){return v.replace(/[|_]+/g," ").replace(/\s+/g," ").trim()}
function parseLabel(text:string,barcode:string){const lines=text.split(/\r?\n/).map(cleanLine).filter(Boolean);const junk=/^(batch|barcode|code|qty|quantity|grey|gray|white|black)$/i;const specOnly=/^(ip\d+|\d+\s*(a|amp|amps|v|vac|volt|volts|hz|mm|cm|m|w|kw)|\d+)$/i;const useful=lines.filter(l=>!junk.test(l)&&!specOnly.test(l)&&l.toLowerCase()!==barcode.toLowerCase()&&l.length>=3);let supplier="";for(const brand of ["Voltex","Clipsal","Hager","NHP","Legrand","Trader","Brilliant","SAL","Pierlite","Deta","HPM","Crompton","Cabac","Middy's","Middy","Schneider"]){if(text.toLowerCase().includes(brand.toLowerCase())){supplier=brand;break}}
 const descriptor=useful.find(l=>/[a-zA-Z]{4,}/.test(l)&&!/batch/i.test(l))||"";const details=useful.filter(l=>l!==descriptor&&/[a-zA-Z]{3,}/.test(l)).slice(0,2).join(" ");let name=[barcode,descriptor,details].filter(Boolean).join(" — ").slice(0,160);if(!name)name=barcode;return {name,supplier,lines}}

export default function MaterialScanPage(){
 const scanner=useRef<HTMLDivElement>(null),audio=useRef<AudioContext|null>(null),lockedCode=useRef<string|null>(null),lastSeen=useRef(0),processing=useRef(false);
 const [running,setRunning]=useState(false),[message,setMessage]=useState("Tap Start camera, then point at one barcode at a time."),[result,setResult]=useState<Result|null>(null),[unknown,setUnknown]=useState<UnknownState|null>(null),[manual,setManual]=useState("");
 function beep(){try{const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)return;if(!audio.current)audio.current=new Ctx();const ctx=audio.current;void ctx.resume();const now=ctx.currentTime;[0,.12].forEach((d,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=i?1040:880;g.gain.setValueAtTime(.0001,now+d);g.gain.exponentialRampToValueAtTime(.18,now+d+.01);g.gain.exponentialRampToValueAtTime(.0001,now+d+.08);o.connect(g);g.connect(ctx.destination);o.start(now+d);o.stop(now+d+.09)})}catch{}}
 async function registerUnknown(barcode:string){if(processing.current)return;processing.current=true;setUnknown({barcode,busy:true});setMessage("New item — reading the label…");try{await loadScript(TESSERACT_SRC,"tesseract-js");const video=scanner.current?.querySelector("video") as HTMLVideoElement|null;if(!video||!video.videoWidth)throw new Error("Camera frame unavailable");const canvas=document.createElement("canvas");const scale=Math.min(1.5,1800/video.videoWidth);canvas.width=Math.round(video.videoWidth*scale);canvas.height=Math.round(video.videoHeight*scale);const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Canvas unavailable");ctx.drawImage(video,0,0,canvas.width,canvas.height);const out=await window.Tesseract.recognize(canvas,"eng",{logger:()=>{}});const parsed=parseLabel(out?.data?.text||"",barcode);if(parsed.name&&parsed.name!==barcode){const r=await fetch("/api/materials/scan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({barcode,name:parsed.name,supplier:parsed.supplier,quantity:1})});const b=await r.json();if(!r.ok)throw new Error(b.error||"Could not save item");setUnknown(null);setResult(b.item);setMessage(`New item saved — ${b.item.name}`);beep();if(navigator.vibrate)navigator.vibrate([60,60,60]);return}setUnknown({barcode,name:parsed.name,supplier:parsed.supplier,busy:false});setMessage("I read the barcode, but the label needs a quick check.")}catch{setUnknown({barcode,busy:false});setMessage("Barcode read. Label text needs a quick check.")}finally{processing.current=false}}
 async function submit(code:string){code=code.trim();if(!code||processing.current)return;setMessage("Checking…");const r=await fetch("/api/materials/scan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({barcode:code})});const b=await r.json();if(!r.ok){setMessage(b.error||"Could not save scan");return}if(b.status==="unknown"){await registerUnknown(code);return}setUnknown(null);setResult(b.item);setMessage(`Added 1 — ${b.item.name}`);beep();if(navigator.vibrate)navigator.vibrate(80)}
 async function start(){try{beep();await loadScript(QUAGGA_SRC,"quagga2-js");if(!scanner.current||!window.Quagga)throw new Error("Scanner unavailable");window.Quagga.init({inputStream:{type:"LiveStream",target:scanner.current,constraints:{facingMode:"environment",width:{ideal:1280},height:{ideal:720}},area:{top:"15%",right:"8%",left:"8%",bottom:"15%"}},locator:{patchSize:"medium",halfSample:true},numOfWorkers:0,frequency:10,decoder:{readers:["code_128_reader","ean_reader","ean_8_reader","upc_reader","upc_e_reader","code_39_reader","code_93_reader","i2of5_reader"]},locate:true},(err:any)=>{if(err){setMessage("Could not start scanner. Check camera permission.");return}window.Quagga.start();setRunning(true);setMessage("Scanning… move each box away after the beep before showing the next one.")});window.Quagga.offDetected();window.Quagga.onDetected((data:any)=>{const code=String(data?.codeResult?.code||"").trim();if(!code)return;lastSeen.current=Date.now();if(lockedCode.current===code)return;lockedCode.current=code;void submit(code)});}catch{setMessage("Scanner could not start. Check camera permission and try again.")}}
 useEffect(()=>{const timer=window.setInterval(()=>{if(lockedCode.current&&Date.now()-lastSeen.current>700)lockedCode.current=null},150);return()=>{clearInterval(timer);try{window.Quagga?.stop()}catch{};audio.current?.close()}},[]);
 return <div className="min-h-screen bg-[#03101f] p-4 text-white"><div className="mx-auto max-w-xl space-y-4"><div className="flex items-center justify-between"><Link href="/materials" className="flex items-center gap-2 text-sm text-[#93a9c2]"><ArrowLeft size={16}/> Materials</Link><span className="text-xs text-[#617993]">Rapid stocktake</span></div><div><h1 className="text-2xl font-semibold">Scan stock</h1><p className="mt-1 text-sm text-[#93a9c2]">New barcode = read the label and create the item. Same barcode later = add one to quantity.</p></div><div className="overflow-hidden rounded-2xl border border-[#168dff55] bg-[#07192b]"><div ref={scanner} className="relative aspect-[4/3] overflow-hidden bg-black [&_canvas]:hidden [&_video]:h-full [&_video]:w-full [&_video]:object-cover"><div className="pointer-events-none absolute inset-[18%_10%] z-10 rounded-xl border-2 border-[#25c7ff]"/></div><div className="p-4"><button onClick={start} disabled={running} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#168dff] py-3 font-semibold disabled:opacity-60"><Camera size={18}/>{running?"Camera running":"Start camera"}</button><p className="mt-3 min-h-5 text-center text-sm text-[#93a9c2]">{message}</p></div></div>{result&&<div className="rounded-2xl border border-[#18d3a055] bg-[#07192b] p-4"><div className="flex items-start gap-3"><Check className="mt-1 text-[#18d3a0]"/><div className="flex-1"><div className="font-semibold">{result.name}</div><div className="mt-1 text-sm text-[#93a9c2]">Quantity now <b className="text-white">{result.onHand}</b> {result.unit}</div></div><button onClick={()=>void submit(result.barcode||"")} className="flex h-10 items-center gap-1 rounded-lg bg-[#09213a] px-3"><Plus size={16}/>1</button></div></div>}{unknown&&<NewBarcode state={unknown} onSaved={b=>{setUnknown(null);setResult(b.item);setMessage(`Saved — ${b.item.name}`);beep()}}/>}<div className="rounded-2xl border border-[#168dff33] bg-[#07192b] p-4"><div className="mb-2 flex items-center gap-2 text-sm font-semibold"><Barcode size={17}/> Enter barcode</div><form onSubmit={e=>{e.preventDefault();void submit(manual);setManual("")}} className="flex gap-2"><input value={manual} onChange={e=>setManual(e.target.value)} placeholder="Barcode number" className="min-w-0 flex-1 rounded-xl border border-[#168dff44] bg-[#041323] px-3 py-3 outline-none"/><button className="rounded-xl bg-[#168dff] px-4 font-semibold">Add</button></form></div></div></div>}
function NewBarcode({state,onSaved}:{state:UnknownState;onSaved:(b:any)=>void}){const[name,setName]=useState(state.name||""),[quantity,setQuantity]=useState("1"),[supplier,setSupplier]=useState(state.supplier||"");useEffect(()=>{setName(state.name||"");setSupplier(state.supplier||"")},[state]);async function save(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/materials/scan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({barcode:state.barcode,name,quantity:Number(quantity),supplier})});const b=await r.json();if(r.ok)onSaved(b)}if(state.busy)return <div className="rounded-2xl border border-[#ff9f1c55] bg-[#07192b] p-5 text-center"><Loader2 className="mx-auto animate-spin text-[#25c7ff]"/><div className="mt-3 font-semibold">Reading product label…</div><div className="mt-1 text-sm text-[#93a9c2]">First scan only. After this barcode is registered, repeats are instant.</div></div>;return <form onSubmit={save} className="rounded-2xl border border-[#ff9f1c55] bg-[#07192b] p-4"><div className="flex items-center gap-2 font-semibold"><PackagePlus size={18} className="text-[#ff9f1c]"/> Check new product</div><div className="mt-1 text-xs text-[#617993]">Barcode {state.barcode}</div><input autoFocus required value={name} onChange={e=>setName(e.target.value)} placeholder="Product name / part number" className="mt-3 w-full rounded-xl border border-[#168dff44] bg-[#041323] px-3 py-3"/><div className="mt-2 grid grid-cols-2 gap-2"><input value={supplier} onChange={e=>setSupplier(e.target.value)} placeholder="Supplier / brand" className="rounded-xl border border-[#168dff44] bg-[#041323] px-3 py-3"/><input type="number" min="1" value={quantity} onChange={e=>setQuantity(e.target.value)} placeholder="Qty" className="rounded-xl border border-[#168dff44] bg-[#041323] px-3 py-3"/></div><button className="mt-3 w-full rounded-xl bg-[#ff9f1c] py-3 font-semibold text-black">Save item</button></form>}
