"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Barcode, Camera, Check, PackagePlus, Plus } from "lucide-react";

type Result={id:string;name:string;onHand:number;unit:string;barcode?:string|null};

declare global { interface Window { BarcodeDetector?: new (options?:{formats?:string[]})=>{detect:(source:ImageBitmapSource)=>Promise<Array<{rawValue:string}>>} } }

export default function MaterialScanPage(){
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),last=useRef<{code:string;at:number}>({code:"",at:0});
 const [running,setRunning]=useState(false),[message,setMessage]=useState("Tap Start camera, then point at one barcode at a time."),[result,setResult]=useState<Result|null>(null),[unknown,setUnknown]=useState<string|null>(null),[manual,setManual]=useState("");
 async function submit(code:string,extra:Record<string,unknown>={}){code=code.trim();if(!code)return;const now=Date.now();if(last.current.code===code&&now-last.current.at<1400)return;last.current={code,at:now};setMessage("Checking…");const r=await fetch("/api/materials/scan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({barcode:code,...extra})});const b=await r.json();if(!r.ok){setMessage(b.error||"Could not save scan");return}if(b.status==="unknown"){setUnknown(code);setResult(null);setMessage("New barcode — confirm the item once.");return}setUnknown(null);setResult(b.item);setMessage(b.status==="incremented"?`Added 1 — ${b.item.name}`:`Saved — ${b.item.name}`);if(navigator.vibrate)navigator.vibrate(80)}
 async function start(){if(!navigator.mediaDevices?.getUserMedia){setMessage("Camera scanning is not available in this browser. Use Enter barcode below.");return}try{stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}}});if(video.current){video.current.srcObject=stream.current;await video.current.play()}setRunning(true);setMessage("Scanning…")}catch{setMessage("Camera permission was blocked. Allow camera access or enter the barcode manually.")}}
 useEffect(()=>{if(!running)return;let cancelled=false;let timer:number;const Detector=window.BarcodeDetector;if(!Detector){setMessage("Live barcode detection is not supported by this browser yet. Use Enter barcode below — duplicate protection still works.");return}const detector=new Detector({formats:["ean_13","ean_8","code_128","code_39","upc_a","upc_e","itf"]});const tick=async()=>{if(cancelled)return;try{if(video.current&&video.current.readyState>=2){const hits=await detector.detect(video.current);if(hits[0]?.rawValue)await submit(hits[0].rawValue)}}catch{}timer=window.setTimeout(tick,180)};void tick();return()=>{cancelled=true;clearTimeout(timer)}},[running]);
 useEffect(()=>()=>stream.current?.getTracks().forEach(t=>t.stop()),[]);
 return <div className="min-h-screen bg-[#03101f] p-4 text-white"><div className="mx-auto max-w-xl space-y-4"><div className="flex items-center justify-between"><Link href="/materials" className="flex items-center gap-2 text-sm text-[#93a9c2]"><ArrowLeft size={16}/> Materials</Link><span className="text-xs text-[#617993]">Rapid stocktake</span></div><div><h1 className="text-2xl font-semibold">Scan stock</h1><p className="mt-1 text-sm text-[#93a9c2]">Same barcode = same item. Every repeat scan adds one to quantity.</p></div><div className="overflow-hidden rounded-2xl border border-[#168dff55] bg-[#07192b]"><div className="relative aspect-[4/3] bg-black"><video ref={video} playsInline muted className="h-full w-full object-cover"/><div className="pointer-events-none absolute inset-[18%_10%] rounded-xl border-2 border-[#25c7ff]"/></div><div className="p-4"><button onClick={start} disabled={running} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#168dff] py-3 font-semibold disabled:opacity-60"><Camera size={18}/>{running?"Camera running":"Start camera"}</button><p className="mt-3 min-h-5 text-center text-sm text-[#93a9c2]">{message}</p></div></div>{result&&<div className="rounded-2xl border border-[#18d3a055] bg-[#07192b] p-4"><div className="flex items-start gap-3"><Check className="mt-1 text-[#18d3a0]"/><div className="flex-1"><div className="font-semibold">{result.name}</div><div className="mt-1 text-sm text-[#93a9c2]">Quantity now <b className="text-white">{result.onHand}</b> {result.unit}</div></div><button onClick={()=>submit(result.barcode||last.current.code)} className="flex h-10 items-center gap-1 rounded-lg bg-[#09213a] px-3"><Plus size={16}/>1</button></div></div>}{unknown&&<NewBarcode barcode={unknown} onSaved={b=>{setUnknown(null);setResult(b.item);setMessage(`Saved — ${b.item.name}`)}}/>}<div className="rounded-2xl border border-[#168dff33] bg-[#07192b] p-4"><div className="mb-2 flex items-center gap-2 text-sm font-semibold"><Barcode size={17}/> Enter barcode</div><form onSubmit={e=>{e.preventDefault();void submit(manual);setManual("")}} className="flex gap-2"><input value={manual} onChange={e=>setManual(e.target.value)} inputMode="numeric" placeholder="Barcode number" className="min-w-0 flex-1 rounded-xl border border-[#168dff44] bg-[#041323] px-3 py-3 outline-none"/><button className="rounded-xl bg-[#168dff] px-4 font-semibold">Add</button></form></div></div></div>}
function NewBarcode({barcode,onSaved}:{barcode:string;onSaved:(b:any)=>void}){const[name,setName]=useState(""),[quantity,setQuantity]=useState("1"),[supplier,setSupplier]=useState("");async function save(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/materials/scan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({barcode,name,quantity:Number(quantity),supplier})});const b=await r.json();if(r.ok)onSaved(b)}return <form onSubmit={save} className="rounded-2xl border border-[#ff9f1c55] bg-[#07192b] p-4"><div className="flex items-center gap-2 font-semibold"><PackagePlus size={18} className="text-[#ff9f1c]"/> New product</div><div className="mt-1 text-xs text-[#617993]">Barcode {barcode}</div><p className="mt-3 text-sm text-[#93a9c2]">This barcode has never been seen. Enter the product name once; future scans will only increase its quantity.</p><input autoFocus required value={name} onChange={e=>setName(e.target.value)} placeholder="Product name / part number" className="mt-3 w-full rounded-xl border border-[#168dff44] bg-[#041323] px-3 py-3"/><div className="mt-2 grid grid-cols-2 gap-2"><input value={supplier} onChange={e=>setSupplier(e.target.value)} placeholder="Supplier / brand" className="rounded-xl border border-[#168dff44] bg-[#041323] px-3 py-3"/><input type="number" min="1" value={quantity} onChange={e=>setQuantity(e.target.value)} placeholder="Qty" className="rounded-xl border border-[#168dff44] bg-[#041323] px-3 py-3"/></div><button className="mt-3 w-full rounded-xl bg-[#ff9f1c] py-3 font-semibold text-black">Save new item</button></form>}
