"use client";
import {useEffect,useRef,useState} from "react";
import Link from "next/link";
import {ArrowLeft,Barcode,Check} from "lucide-react";
declare global{interface Window{Quagga?:any}}
const BUILD="scanner-r7-2026-08-27";
const Q="https://cdn.jsdelivr.net/npm/@ericblade/quagga2@1.8.4/dist/quagga.min.js";
function script(){return new Promise<void>((ok,no)=>{const e=document.getElementById("quagga-r7")as HTMLScriptElement|null;if(e){if(e.dataset.loaded==="1")ok();else e.addEventListener("load",()=>ok(),{once:true});return}const s=document.createElement("script");s.id="quagga-r7";s.src=Q;s.async=true;s.onload=()=>{s.dataset.loaded="1";ok()};s.onerror=no;document.head.appendChild(s)})}
export default function ScannerR7(){const cam=useRef<HTMLDivElement>(null),busy=useRef(false),lock=useRef("");const[status,setStatus]=useState("Starting camera…"),[photo,setPhoto]=useState(""),[code,setCode]=useState(""),[review,setReview]=useState(false),[known,setKnown]=useState(false),[itemName,setItemName]=useState(""),[manual,setManual]=useState("");
function stop(){try{window.Quagga?.offDetected();window.Quagga?.stop()}catch{}if(cam.current)cam.current.innerHTML=""}
function snap(){const v=cam.current?.querySelector("video")as HTMLVideoElement|null;if(!v?.videoWidth)return null;const c=document.createElement("canvas");c.width=Math.min(v.videoWidth,1200);c.height=Math.round(v.videoHeight*c.width/v.videoWidth);c.getContext("2d")?.drawImage(v,0,0,c.width,c.height);return c}
async function capture(barcode:string){if(busy.current||review)return;const c=snap();if(!c)return;busy.current=true;stop();const data=c.toDataURL("image/jpeg",.78);setCode(barcode);setPhoto(data);setReview(true);setStatus("PHOTO CAPTURED — nothing saved yet");try{const r=await fetch(`/api/materials/scan?barcode=${encodeURIComponent(barcode)}`);const b=await r.json();setKnown(Boolean(b.known));setItemName(b.item?.name||"");setStatus(b.known?`KNOWN ITEM — ${b.item?.name||barcode}`:"NEW BARCODE — enter/select item name, then tick")}catch{setStatus("Could not check barcode — enter item name")};busy.current=false}
function reset(){stop();busy.current=false;lock.current="";setPhoto("");setCode("");setReview(false);setKnown(false);setItemName("");setStatus("Restarting camera…");setTimeout(()=>void start(),250)}
async function queue(){if(!known&&!itemName.trim()){setStatus("Enter the item name from the label first");return}if(busy.current)return;busy.current=true;setStatus("QUEUING PHOTO — server will read this box quantity");try{if(!known){const create=await fetch("/api/materials/scan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({barcode:code,quantity:1,name:itemName.trim()})});if(!create.ok){const b=await create.json().catch(()=>({}));throw new Error(b.error||"Could not create item")}}
const r=await fetch("/api/materials/scan-queue",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({barcode:code,dataUrl:photo})});const b=await r.json();if(!r.ok)throw new Error(b.error||"Queue failed");setStatus("QUEUED ✓ — scan next box");setTimeout(reset,450)}catch(e){setStatus(`NOT QUEUED — ${e instanceof Error?e.message:"try again"}`);busy.current=false}}
async function start(){try{await script();if(!cam.current)return;stop();window.Quagga.init({inputStream:{type:"LiveStream",target:cam.current,constraints:{facingMode:"environment",width:{ideal:1920},height:{ideal:1080}},area:{top:"8%",right:"3%",left:"3%",bottom:"8%"}},locator:{patchSize:"medium",halfSample:true},numOfWorkers:0,frequency:18,decoder:{readers:["code_128_reader","ean_reader","ean_8_reader","upc_reader","upc_e_reader","code_39_reader","code_93_reader","i2of5_reader"]},locate:true},(e:any)=>{if(e){setStatus("Camera failed — retry");return}window.Quagga.start();setStatus("READY — barcode + full label in frame")});window.Quagga.onDetected((d:any)=>{const c=String(d?.codeResult?.code||"").trim();if(!c||busy.current||review||lock.current===c)return;lock.current=c;void capture(c)})}catch{setStatus("Camera failed — retry")}}
useEffect(()=>{void start();return stop},[]);
return <div className="min-h-screen bg-[#03101f] p-4 text-white"><div className="mx-auto max-w-xl space-y-4"><div className="flex items-center justify-between"><Link href="/materials" className="flex items-center gap-2 text-sm text-[#93a9c2]"><ArrowLeft size={16}/> Materials</Link><span className="text-[11px] text-[#5f7894]">{BUILD}</span></div><h1 className="text-3xl font-semibold">Scan Stock</h1><div className="overflow-hidden rounded-2xl border border-[#168dff55] bg-[#07192b]"><div className="relative aspect-[4/3] overflow-hidden bg-black"><div ref={cam} className={`absolute inset-0 [&_canvas]:hidden [&_video]:h-full [&_video]:w-full [&_video]:object-cover ${review?"hidden":"block"}`}/>{review&&photo&&<img src={photo} alt="captured label" className="absolute inset-0 h-full w-full object-fill"/>}{!review&&<div className="pointer-events-none absolute inset-[8%_3%] rounded-xl border-4 border-[#25c7ff]"/>}</div><div className="p-4 text-center font-semibold text-[#18d3a0]">{status}</div></div>{review&&<div className="rounded-2xl border border-[#18d3a055] bg-[#07192b] p-4"><div className="text-xl font-semibold">{known?"Item recognised":"Teach this barcode"}</div><div className="mt-1 text-sm text-[#93a9c2]">Barcode {code}. Quantity is read from THIS box photo on the server.</div>{known?<div className="mt-4 rounded-xl border border-[#18d3a055] bg-[#0b302c] p-4"><Check className="mr-2 inline"/> {itemName}</div>:<><div className="mt-4 text-sm text-[#93a9c2]">Item name from label</div><input value={itemName} onChange={e=>setItemName(e.target.value)} placeholder="e.g. HYMF5 Mounting Flange 18mm Shallow" className="mt-2 w-full rounded-xl border border-[#168dff44] bg-[#041323] px-3 py-4 text-lg"/></>}<button type="button" onClick={()=>void queue()} className="mt-4 w-full rounded-xl bg-[#18d3a0] py-4 text-lg font-bold text-[#03101f]"><Check className="mr-2 inline"/>{known?"Confirm & Scan Next":"Teach Item & Confirm"}</button><button type="button" onClick={reset} className="mt-2 w-full rounded-xl border border-[#168dff44] py-3">Cancel / Scan Next</button></div>}{!review&&<div className="rounded-2xl border border-[#168dff33] bg-[#07192b] p-4"><div className="mb-2 flex items-center gap-2 font-semibold"><Barcode size={17}/> Enter barcode</div><form onSubmit={e=>{e.preventDefault();const c=manual.trim();if(c){void capture(c);setManual("")}}} className="flex gap-2"><input value={manual} onChange={e=>setManual(e.target.value)} placeholder="Barcode number" className="min-w-0 flex-1 rounded-xl border border-[#168dff44] bg-[#041323] px-3 py-3"/><button className="rounded-xl bg-[#168dff] px-4 font-semibold">Add</button></form></div>}</div></div>}
